/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-12-28 15:00:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.rweb.networksimilarity;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>Network Fingerprint Scanner</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<style>\r\n");
      out.write("\t.control-group.warning > label,\r\n");
      out.write("\t.control-group.warning .help-block,\r\n");
      out.write("\t.control-group.warning .help-inline {\r\n");
      out.write("\t  color: #c09853;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.control-group.warning input,\r\n");
      out.write("\t.control-group.warning select,\r\n");
      out.write("\t.control-group.warning textarea {\r\n");
      out.write("\t  color: #c09853;\r\n");
      out.write("\t /* border-color: #c09853;*/\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.control-group.warning input:focus,\r\n");
      out.write("\t.control-group.warning select:focus,\r\n");
      out.write("\t.control-group.warning textarea:focus {\r\n");
      out.write("\t  /*border-color: #a47e3c;*/\r\n");
      out.write("\t  -webkit-box-shadow: 0 0 6px #dbc59e;\r\n");
      out.write("\t     -moz-box-shadow: 0 0 6px #dbc59e;\r\n");
      out.write("\t          box-shadow: 0 0 6px #dbc59e;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.control-group.warning .input-prepend .add-on,\r\n");
      out.write("\t.control-group.warning .input-append .add-on {\r\n");
      out.write("\t  color: #c09853;\r\n");
      out.write("\t  background-color: #fcf8e3;\r\n");
      out.write("\t  /*border-color: #c09853;*/\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.control-group.error > label,\r\n");
      out.write("\t.control-group.error .help-block,\r\n");
      out.write("\t.control-group.error .help-inline {\r\n");
      out.write("\t  color: #b94a48;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.control-group.error input,\r\n");
      out.write("\t.control-group.error select,\r\n");
      out.write("\t.control-group.error textarea {\r\n");
      out.write("\t  color: #b94a48;\r\n");
      out.write("\t  /*border-color: #b94a48;*/\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.control-group.error input:focus,\r\n");
      out.write("\t.control-group.error select:focus,\r\n");
      out.write("\t.control-group.error textarea:focus {\r\n");
      out.write("\t  /*border-color: #953b39;*/\r\n");
      out.write("\t  -webkit-box-shadow: 0 0 6px #d59392;\r\n");
      out.write("\t     -moz-box-shadow: 0 0 6px #d59392;\r\n");
      out.write("\t          box-shadow: 0 0 6px #d59392;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.control-group.error .input-prepend .add-on,\r\n");
      out.write("\t.control-group.error .input-append .add-on {\r\n");
      out.write("\t  color: #b94a48;\r\n");
      out.write("\t  background-color: #f2dede;\r\n");
      out.write("\t /* border-color: #b94a48;*/\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.control-group.success > label,\r\n");
      out.write("\t.control-group.success .help-block,\r\n");
      out.write("\t.control-group.success .help-inline {\r\n");
      out.write("\t  color: #468847;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.control-group.success input,\r\n");
      out.write("\t.control-group.success select,\r\n");
      out.write("\t.control-group.success textarea {\r\n");
      out.write("\t  color: #468847;\r\n");
      out.write("\t  /*border-color: #468847;*/\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.control-group.success input:focus,\r\n");
      out.write("\t.control-group.success select:focus,\r\n");
      out.write("\t.control-group.success textarea:focus {\r\n");
      out.write("\t  /*border-color: #356635;*/\r\n");
      out.write("\t  -webkit-box-shadow: 0 0 6px #7aba7b;\r\n");
      out.write("\t     -moz-box-shadow: 0 0 6px #7aba7b;\r\n");
      out.write("\t          box-shadow: 0 0 6px #7aba7b;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.control-group.success .input-prepend .add-on,\r\n");
      out.write("\t.control-group.success .input-append .add-on {\r\n");
      out.write("\t  color: #468847;\r\n");
      out.write("\t  background-color: #dff0d8;\r\n");
      out.write("\t  /*border-color: #468847;*/\r\n");
      out.write("\t}\r\n");
      out.write("\t.help-block,\r\n");
      out.write("\t.help-inline {\r\n");
      out.write("\t  color: #555555;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.help-block {\r\n");
      out.write("\t  display: block;\r\n");
      out.write("\t  margin-bottom: 9px;\r\n");
      out.write("\t  padding-left:10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.help-inline {\r\n");
      out.write("\t  display: inline-block;\r\n");
      out.write("\t  *display: inline;\r\n");
      out.write("\t  padding-left: 5px;\r\n");
      out.write("\t  vertical-align: middle;\r\n");
      out.write("\t  *zoom: 1;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script src=\"rweb/js/bootstrap-validator/jqBootstrapValidation.js\"></script>\r\n");
      out.write("\t<script src=\"rweb/js/login.js\"></script>\r\n");
      out.write("\t<script src=\"static/js/login.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"modal fade\" id=\"loginModal\" style=\"overflow: hidden;top:25%;margin:0 auto;width:400px;\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"loginModalLabel\">\r\n");
      out.write("\t  <div class=\"modal-dialog\" style=\"border:none;\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t<div class=\"login-box\" style=\"margin:0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t <button type=\"button\" style=\"margin-top:-8px;color:white;\" class=\"close\" \r\n");
      out.write("\t\t\t               data-dismiss=\"modal\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t                  &times;\r\n");
      out.write("\t\t\t            </button>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\tLogin to NFP\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-horizontal login\" id=\"loginForm\" method=\"post\" action=\"\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<fieldset class=\"col-sm-12\" style=\"border:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-12\" style=\"width:340px;margin:0 auto;\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"username\" class=\"form-control\" id=\"loginusername\" placeholder=\"Username or E-mail\" minlength=\"6\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"fa fa-user\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-12\" style=\"width:340px;margin:0 auto;margin-top:15px;\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" class=\"form-control\" id=\"loginpassword\" placeholder=\"Password\" minlength=\"6\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"fa fa-key\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\" style=\"margin:0 auto;margin-top:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" onclick=\"logins();\" class=\"btn btn-lg btn-primary col-xs-12 \">Login</button>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- \t<a class=\"pull-left\" href=\"javascript:void(0);\" onclick=\"forgotPassword();\" style=\"margin-left:12px;\">Forgot Password?</a> -->\r\n");
      out.write("\t\t\t\t\t\t<a class=\"pull-right\" href=\"javascript:void(0);\" onclick=\"signUp();\" style=\"margin-right:12px;\">Sign Up!</a>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"></div>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"modal fade\" id=\"signupModal\" style=\"overflow: hidden;top:20%;margin:0 auto;width:400px;\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"signupModalLabel\">\r\n");
      out.write("\t  <div class=\"modal-dialog\" style=\"border:none;\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"login-box\" style=\"margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" style=\"margin-top:-8px;color:white;\" class=\"close\" \r\n");
      out.write("\t\t\t               data-dismiss=\"modal\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t                  &times;\r\n");
      out.write("\t\t\t            </button>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\tCreate new account\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-horizontal register\"  method=\"post\" id=\"registerForm\" >\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<fieldset class=\"col-sm-12\" style=\"border: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group control-group\">\t\t\t\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-12\" style=\"width:364px;margin:0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"username\" placeholder=\"Username\" id=\"signusername\" minlength=\"6\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group control-group\">\t\t\t\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-12\" style=\"width:364px;margin:0 auto;margin-top:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" name=\"email\" placeholder=\"Email Address\" id=\"signemail\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\t\t\t\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-12\" style=\"width:364px;margin:0 auto;margin-top:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"Password\" id=\"signpassword\" minlength=\"6\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\t\t\t\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-12\" style=\"width:364px;margin:0 auto;margin-top:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"comfirmpassword\" placeholder=\"Confirm Password\" id=\"signcomfirmpassword\" minlength=\"6\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <div class=\"confirm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"agree\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"agree\">I agree to <a href=\"page-register.html#\">Term of Use</a></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\" style=\"margin-top:20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" id=\"registerBtn\" class=\"btn btn-primary btn-lg col-xs-12\">Create Account!</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</form>\t\t\t\r\n");
      out.write("\t\t\t\t</div>\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myinfoModal\" style=\"top:25%;margin:0 auto;width:520px;\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myinfoModalLabel\">\r\n");
      out.write("\t  <div class=\"modal-dialog\" style=\"border:none;\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"box border\">\r\n");
      out.write("\t\t\t<div class=\"box-title\">\r\n");
      out.write("\t\t\t\t<h4><i class=\"fa fa-check-square-o\"></i>System Info</h4>\r\n");
      out.write("\t\t\t\t<div class=\"tools\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\" data-dismiss=\"modal\" aria-label=\"Close\" class=\"remove\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"box-body\">\r\n");
      out.write("\t\t\t\tSign Up failed!\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"modal fade\" id=\"loginfoModal\" style=\"top:25%;margin:0 auto;width:520px;\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"loginfoModalLabel\">\r\n");
      out.write("\t  <div class=\"modal-dialog\" style=\"border:none;\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"box border\">\r\n");
      out.write("\t\t\t<div class=\"box-title\">\r\n");
      out.write("\t\t\t\t<h4><i class=\"fa fa-check-square-o\"></i>System Info</h4>\r\n");
      out.write("\t\t\t\t<div class=\"tools\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\" data-dismiss=\"modal\" aria-label=\"Close\" class=\"remove\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"box-body\">\r\n");
      out.write("\t\t\t\tLogin failed!\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- YDJ -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"modal fade\" id=\"forgotPasswordModal\" style=\"overflow: hidden;top:20%;margin:0 auto;width:400px;\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"signupModalLabel\">\r\n");
      out.write("\t  <div class=\"modal-dialog\" style=\"border:none;\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"login-box\" style=\"margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" style=\"margin-top:-8px;color:white;\" class=\"close\" \r\n");
      out.write("\t\t\t               data-dismiss=\"modal\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t                  &times;\r\n");
      out.write("\t\t\t            </button>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t\tForgot Password\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-horizontal register\" method=\"post\" action=\"networksimilarity/signup.form?url=");
      out.print(request.getHeader("Referer"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<fieldset class=\"col-sm-12\" style=\"border: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group control-group\">\t\t\t\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-12\" style=\"width:364px;margin:0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"username\" placeholder=\"Username\" id=\"signusername\" minlength=\"6\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group control-group\">\t\t\t\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-12\" style=\"width:364px;margin:0 auto;margin-top:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" name=\"email\" placeholder=\"Email Address\" id=\"signemail\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\t\t\t\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-12\" style=\"width:364px;margin:0 auto;margin-top:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"Password\" id=\"signpassword\" minlength=\"6\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\t\t\t\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"controls row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-12\" style=\"width:364px;margin:0 auto;margin-top:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"comfirmpassword\" placeholder=\"Confirm Password\" id=\"signcomfirmpassword\" minlength=\"6\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <div class=\"confirm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"agree\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"agree\">I agree to <a href=\"page-register.html#\">Term of Use</a></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\" style=\"margin-top:20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary btn-lg col-xs-12\">Create Account!</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</form>\t\t\t\r\n");
      out.write("\t\t\t\t</div>\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"tipModal\" style=\"top:15%;\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"selectFileModalLabel\">\r\n");
      out.write("\t  <div class=\"modal-dialog\" style=\"border:none;width: 400px;\" role=\"document\" >\r\n");
      out.write("\t\t<div class=\"box border\">\r\n");
      out.write("\t\t\t<div class=\"box-title\">\r\n");
      out.write("\t\t\t\t<h4><i class=\"fa fa-check-square-o\"></i>Tip</h4>\r\n");
      out.write("\t\t\t\t<div class=\"tools\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\" data-dismiss=\"modal\" aria-label=\"Close\" class=\"remove\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"box-body\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("                    <div class=\"form-group\"  align=\"center\">\r\n");
      out.write("                        <label class=\"\" id=\"tipInfo\" style=\"width: 100%;\"></label>\r\n");
      out.write("                        <div class=\"col-md-9\">\r\n");
      out.write("                            <div class=\"fileupload fileupload-new\" style=\"margin-bottom:0;\" data-provides=\"fileupload\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\" style=\"padding: 10px 0 0 0;margin-top:0px;\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\" aria-label=\"Close\" >OK</button>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t<!-- END YDJ -->\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
