/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-01-31 05:39:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.rweb.networksimilarity;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class networksimilarityAnalysis_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    <title>Network Fingerprint Scanner</title>\r\n");
      out.write("\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"static/image/w1.png\"   type=\"image/x-icon\"/>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tif (navigator.userAgent.split(\";\")[1].toLowerCase().indexOf(\"msie\") > 0 ){\r\n");
      out.write("\t\t\t\twindow.location.href = \"supportInfo\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t    <!-- Css files -->\r\n");
      out.write("\t\t<link href=\"rweb/css/header.css\"  type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("\t   \t<link rel=\"stylesheet\" href=\"//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t    <link href=\"rweb/assets/css/style.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<link href=\"rweb/css/header.css\"  type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"rweb/css/comment.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"rweb/assets/js/bootstrap-fileupload/bootstrap-fileupload.min.css\" />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\t.action-item {\r\n");
      out.write("\t\t\t    display: inline-block;\r\n");
      out.write("\t\t\t    padding-right: .5rem;\r\n");
      out.write("\t\t\t    padding-left: .25rem;\r\n");
      out.write("\t\t\t    border-right-width: 1px;\r\n");
      out.write("\t\t\t    border-right-style: solid;\r\n");
      out.write("\t\t\t\t    line-height: 1.25rem;\r\n");
      out.write("\t\t\t    font-size: 1rem;\r\n");
      out.write("\t\t\t    color: #999;\r\n");
      out.write("\t\t\t    text-transform: uppercase;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.action-item a{\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.radio-inline, .checkbox-inline{\r\n");
      out.write("\t\t\t\tline-height:22px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"sticky-header-on tablet-sticky-header\" style=\"padding-bottom:0;\tfont-size:medium\r\n");
      out.write("; line-height: 1.5em\">\r\n");
      out.write("\t\t<noscript>\r\n");
      out.write("\t<div class=\"modal-backdrop fade in\" style=\"z-index: 20000;\"></div>\r\n");
      out.write("\t<div class=\"modal fade\" style=\"top:30%;display:block;opacity:1;z-index: 200000;\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"selectFileModalLabel\">\r\n");
      out.write("\t  <div class=\"modal-dialog\" style=\"border:none;width: 500px;height: 150px;\" role=\"document\" >\r\n");
      out.write("\t\t<div class=\"box border\">\r\n");
      out.write("\t\t\t<div class=\"box-title\">\r\n");
      out.write("\t\t\t\t<h4><i class=\"fa fa-check-square-o\"></i>JavaScript needs to be enabled</h4>\r\n");
      out.write("\t\t\t\t<div class=\"tools\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"box-body\">\r\n");
      out.write("\t\t\t\t<p>NFPscanner requires JavaScript to run properly. Please enable JavaScript, and then reload this page.</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<p>You can find instructions on how to enable JavaScript for your browser below:</p>\r\n");
      out.write("\t\t\t\t<div style=\"height:100px;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"http://www.google.com/support/chrome/bin/answer.py?answer=114662\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui-browserupdate-icon chrome\"><span class=\"ui-browserupdate-name\">Chrome</span></div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<a href=\"http://docs.info.apple.com/article.html?path=Safari/5.0/en/9279.html\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui-browserupdate-icon safari\"><span class=\"ui-browserupdate-name\">Safari</span></div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<a href=\"http://support.mozilla.com/en-US/kb/JavaScript\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui-browserupdate-icon firefox\"><span class=\"ui-browserupdate-name\">Firefox</span></div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<a href=\"http://support.microsoft.com/gp/howtoscript\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui-browserupdate-icon msie\"><span class=\"ui-browserupdate-name\">Internet Explorer</span></div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</noscript>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<header id=\"\" class=\"sticky-header\" style=\"opacity: 1;padding:0;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Main Header -->\r\n");
      out.write("\t\t\t\t<div id=\"main-header\" style=\"height: 80px;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"logo\" class=\"col-lg-12 col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"static/image/b2.png\" style=\"width: 110px;margin-top: -20px;margin-right: -20px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<span style=\"color:white;font-size:33px;margin-top: 1px;\">Network Fingerprint Scanner</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span style=\"color: white; font-size: 15px; top: 28px; margin-left: 5px;\">NFPscanner:a server for knowledge-based characterization of biomedical networks\r\n");
      out.write("</span> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /Main Header -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Lower Header -->\r\n");
      out.write("\t\t\t\t<div id=\"lower-header\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"menu-button\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span>Menu</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul id=\"navigation\" style=\"\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li >\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa \" href=\"networksimilarityHome.html\">Home</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li  style=\"width: 300px;\" id=\"Fingerprint\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityAnalysis?type=1\" onclick=\"changeSubTab('networksimilarityAnalysis_1',this,2)\">Network Fingerprint Scan</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"width: 250px;\" id=\"Alignment\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityAnalysis?type=2\" onclick=\"changeSubTab('networksimilarityAnalysis_3',this,1)\">Pairwise Alignment</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa \" href=\"networksimilaritystatistical\">Resource</a>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityHelp\">Help</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityContact\">Contact</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal fade\" id=\"selectFileModal\" style=\"top:25%;margin:0 auto;width:620px;\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"selectFileModalLabel\">\r\n");
      out.write("\t  <div class=\"modal-dialog\" style=\"border:none;\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"box border\">\r\n");
      out.write("\t\t\t<div class=\"box-title\">\r\n");
      out.write("\t\t\t\t<h4><i class=\"fa fa-check-square-o\"></i>Upload File</h4>\r\n");
      out.write("\t\t\t\t<div class=\"tools\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\" data-dismiss=\"modal\" aria-label=\"Close\" class=\"remove\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"box-body\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-md-3 control-label\">Input File:</label>\r\n");
      out.write("                        <div class=\"col-md-9\">\r\n");
      out.write("                            <div class=\"fileupload fileupload-new\" style=\"margin-bottom:0;\" data-provides=\"fileupload\">\r\n");
      out.write("                            \t<span class=\"form-control fileupload-preview\" style=\"float: left;width:150px;\" ></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"btn btn-default btn-file\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"fileupload-new\">Add file</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"fileupload-exists\">Change</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"file\" id=\"file\" flag=\"0\" class=\"file-input\"  >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" id=\"removeFileBtn\" class=\"btn btn-danger fileupload-exists\" data-dismiss=\"fileupload\">Remove</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("           \t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t <div class=\"form-group\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 \" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\" style=\"margin-bottom:0;width: 620px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"col-md-3 control-label\" for=\"input-small\" >ID Type:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select class=\"form-control select2\" style=\"width: 180px;float: left;margin-left: 5px;\" id=\"idTypeUpload\" name=\"idType\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"GeneSymbol\">GeneSymbol</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"ENSEMBL\">ENSEMBL</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"REFSEQ_PROTEIN\">REFSEQ_PROTEIN</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"REFSEQ_RNA\">REFSEQ_RNA</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"UNIPROT\">UNIPROT</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"HGNC\">HGNC</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Entrez\" selected id=\"loadSampleOption\">Entrez</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"\" style=\"float: left;margin-left: 10px;margin-top: 5px;\" >Specify if necessary. </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("                </form>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\" style=\"padding: 10px 0 0 0;margin-top:0px;\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"okUpload\" flag=\"\" onclick=\"submitUploadFile()\">OK</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<section id=\"content\" style=\"min-height: 1400px;\" id=\"section1\" >\r\n");
      out.write("\t<section class=\"section full-width-bg\" style=\"padding-top:5px;\">\r\n");
      out.write("\t\t\t\t<ol class=\"breadcrumb\" id=\"breadcrumb\" style=\"margin:10px 0 0 0;display: none;\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"networksimilarityAnalysis\" style=\"font-size: 15px;\">Analysis</a></li>\r\n");
      out.write("\t\t\t\t\t<li><span id=\"analysisName\" style=\"font-size: 15px;\">NetworkFingerPrint</span></li>\r\n");
      out.write("\t\t\t\t\t<span style=\"float:right;padding:0 10px;\" class=\"btn btn-default\" onclick=\"startIntro()\">Tutorials</span>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t<iframe width=\"100%\" style=\"min-height: 1450px;\" onload=\"iFrameHeight('pariwiseIframe')\" frameborder=\"no\" scrolling=\"no\" border=\"0\" id=\"pariwiseIframe\" name=\"pariwiseIframe\" ></iframe>\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t<!-- Footer -->\r\n");
      out.write("\t\t\t<footer id=\"footer1\" >\r\n");
      out.write("\t\t\t\t<!-- Lower Footer -->\r\n");
      out.write("\t\t\t\t<div id=\"lower-footer\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-4\" style=\"opacity: 1;width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t <p class=\"copyright\">NFPscanner is supported by a grant from National Nature Science Foundation of China.\r\n");
      out.write("\t\t\t\t\t\t\t\t </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t <p class=\"copyright\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Copyright © 2015-2016 Beijing Institute of Radiation Medicine</p>\r\n");
      out.write(" \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("<input type=\"hidden\" id=\"play\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"modal fade\" id=\"tipModal1\" style=\"top:15%;\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"selectFileModalLabel\">\r\n");
      out.write("\t  <div class=\"modal-dialog\" style=\"border:none;width: 400px;\" role=\"document\" >\r\n");
      out.write("\t\t<div class=\"box border\">\r\n");
      out.write("\t\t\t<div class=\"box-title\">\r\n");
      out.write("\t\t\t\t<h4><i class=\"fa fa-check-square-o\"></i>Tip</h4>\r\n");
      out.write("\t\t\t\t<div class=\"tools\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\" data-dismiss=\"modal\" id=\"tipXBtn\" aria-label=\"Close\" class=\"remove\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"box-body\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("                    <div class=\"form-group\"  align=\"center\">\r\n");
      out.write("                        <label class=\"\" id=\"tipInfo1\" style=\"width: 100%;\"></label>\r\n");
      out.write("                        <div class=\"col-md-9\">\r\n");
      out.write("                            <div class=\"fileupload fileupload-new\" style=\"margin-bottom:0;\" data-provides=\"fileupload\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"static/image/loading.gif\"  id=\"imgLoading\" style=\"display: none;\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\" style=\"padding: 10px 0 0 0;margin-top:0px;\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" id=\"tipCancelBtn\" style=\"display: none;\" class=\"btn btn-default\" data-dismiss=\"modal\" >Cancel</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\" aria-label=\"Close\" id=\"tipOKBtn\" >OK</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"modal fade\" id=\"skipModal\" style=\"top:15%;\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"skipModalLabel\">\r\n");
      out.write("\t  <div class=\"modal-dialog\" style=\"border:none;width: 400px;\" role=\"document\" >\r\n");
      out.write("\t\t<div class=\"box border\">\r\n");
      out.write("\t\t\t<div class=\"box-title\">\r\n");
      out.write("\t\t\t\t<h4><i class=\"fa fa-check-square-o\"></i>System info</h4>\r\n");
      out.write("\t\t\t\t<div class=\"tools\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\" data-dismiss=\"modal\" id=\"skipTipBtn\" aria-label=\"Close\" class=\"remove\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"box-body\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("                    <div class=\"form-group\"  align=\"center\">\r\n");
      out.write("                        <label class=\"\" id=\"skipTipLabel\" style=\"width: 100%;\"></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\" style=\"padding: 10px 0 0 0;margin-top:0px;\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" id=\"stillbtn\" class=\"btn btn-default\" data-dismiss=\"modal\" >Still run</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\" aria-label=\"Close\" id=\"skipbtn\" >Skip</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t <div class=\"modal fade\" id=\"tipModalLoading\" style=\"top:30%;\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"selectFileModalLabel\">\r\n");
      out.write("\t  <div class=\"modal-dialog\" style=\"border:none;width: 250px;height: 150px;\" role=\"document\" >\r\n");
      out.write("\t\t<div class=\"box border\">\r\n");
      out.write("\t\t\t<div class=\"box-title\">\r\n");
      out.write("\t\t\t\t<h4><i class=\"fa fa-check-square-o\"></i>Tip</h4>\r\n");
      out.write("\t\t\t\t<div class=\"tools\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"box-body\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\">\r\n");
      out.write("                    <div class=\"form-group\"  align=\"center\">\r\n");
      out.write("                        <div class=\"col-md-9\">\r\n");
      out.write("                            <div class=\"fileupload fileupload-new\" style=\"margin-bottom:0;\" align=\"center\" data-provides=\"fileupload\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"static/image/loading.gif\"  id=\"imgLoading\" width=\"100px;\" style=\"margin-left: 65px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"modal fade\" id=\"tipformatModal\" style=\"top:15%;\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"selectFileModalLabel\">\r\n");
      out.write("\t  <div class=\"modal-dialog\" style=\"border:none;width: 500px;\" role=\"document\" >\r\n");
      out.write("\t\t<div class=\"box border\">\r\n");
      out.write("\t\t\t<div class=\"box-title\">\r\n");
      out.write("\t\t\t\t<h4><i class=\"fa fa-check-square-o\"></i>Tip</h4>\r\n");
      out.write("\t\t\t\t<div class=\"tools\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"box-body\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\">\r\n");
      out.write("                    <div class=\"form-group\"  align=\"center\">\r\n");
      out.write("                        <label class=\"\" id=\"tipInfo\" style=\"width: 100%;\">To verify the format, please choose!</label>\r\n");
      out.write("                        <div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"control-label col-md-1\" style=\"margin-left: 10px;width: 120px;\" >Format Type:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select class=\"form-control\" style=\"width: 200px;\" id=\"formatType\" name=\"formatType\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=edgelist>edgelist</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"graphml\">graphml</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"gml\">gml</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"formatHid\"/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"control-label col-md-1\" style=\"margin-left: 10px;width: 120px;\" >ID Type:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select class=\"form-control select2\" style=\"width: 200px;\" id=\"idTypeUploadformat\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"GeneSymbol\">GeneSymbol</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"ENSEMBL\">ENSEMBL</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"REFSEQ_PROTEIN\">REFSEQ_PROTEIN</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"REFSEQ_RNA\">REFSEQ_RNA</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"UNIPROT\">UNIPROT</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"HGNC\">HGNC</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Entrez\" selected id=\"loadSampleOption\">Entrez</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"formatHid1\"/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\" style=\"padding: 10px 0 0 0;margin-top:0px;\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\" aria-label=\"Close\" onclick=\"formatOK();\" >OK</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<input type=\"hidden\" id='libraryHidden'>\r\n");
      out.write("\t<script src=\"http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"rweb/assets/js/bootstrap-fileupload/bootstrap-fileupload.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tvar REQUEST_TYPE = '");
      out.print(request.getParameter("type"));
      out.write("';\r\n");
      out.write("\tvar play = '");
      out.print(request.getParameter("play"));
      out.write("';\r\n");
      out.write("\tvar ID = '");
      out.print(request.getParameter("id"));
      out.write("';\r\n");
      out.write("\tvar library = '");
      out.print(request.getParameter("library"));
      out.write("';\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\tif(REQUEST_TYPE != null){\r\n");
      out.write("\t\t\t$(\"#analysis\" + REQUEST_TYPE).trigger(\"click\");\r\n");
      out.write("\t\t\tif(REQUEST_TYPE==1){\r\n");
      out.write("\t\t\t\t$(\"#Fingerprint\").addClass('current-menu-item');\r\n");
      out.write("\t\t\t\tdocument.getElementById('pariwiseIframe').src = 'networksimilarityAnalysis_1';\r\n");
      out.write("\t\t\t\t$(\"#analysisName\").html('Network fingerprint scan');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(REQUEST_TYPE==2){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\"#Alignment\").addClass('current-menu-item');\r\n");
      out.write("\t\t\t\tdocument.getElementById('pariwiseIframe').src = 'networksimilarityAnalysis_3';\r\n");
      out.write("\t\t\t\t$(\"#analysisName\").html('Pairwase Alignment');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(play != undefined&& play != null && play == \"1\"){\r\n");
      out.write("\t\t\t$(\"#play\").val(play);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tif(library!=undefined&&library!=null){\r\n");
      out.write("\t\t\t$(\"#libraryHidden\").val(library);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction iFrameHeight(id) {\r\n");
      out.write("\t\t$(\"body\").scrollTop(0);\r\n");
      out.write("\t    var ifm = document.getElementById(id);\r\n");
      out.write("\t    var subWeb = document.frames ? document.frames[\"iframe\"].document : ifm.contentDocument;\r\n");
      out.write("\t    if (ifm != null && subWeb != null) {\r\n");
      out.write("\t         ifm.height = subWeb.body.scrollHeight;\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeSubTab(type,obj,num){\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"body\").scrollTop(0);\r\n");
      out.write("\t\t$(\"#topAnalysis\").trigger(\"click\");\r\n");
      out.write("\t\tdocument.getElementById('pariwiseIframe').src = type;\r\n");
      out.write("\t\t$(\"#analysisName\").html($(obj).text());\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeTab(type,obj){\r\n");
      out.write("\t\t$(\"body\").scrollTop(0);\r\n");
      out.write("\t\tvar jobID = $(\"#jobTitle\",window.frames['pariwiseIframe'].document).val();\r\n");
      out.write("\t\tif(type == 2){\r\n");
      out.write("\t\t \tif(ID == undefined||ID==\"\"||ID=='null'){\r\n");
      out.write("\t\t \t\treturn;\r\n");
      out.write("\t\t\t\twindow.location.href = 'networksimilarityAnalysis';\r\n");
      out.write("\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t \t\t\twindow.location.href = 'networksimilarityResult_2?&id=' + ID;\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\"#pariwiseIframe,#breadcrumb\").hide();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t\t$(\"#resultIframe\").attr(\"src\",\"networksimilarityResult\");\r\n");
      out.write("\t\t\t$(obj).parent().prev().removeClass(\"current-menu-item\");\r\n");
      out.write("\t\t\t$(obj).parent().addClass(\"current-menu-item\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#resultIframe\").hide();\r\n");
      out.write("\t\t\t$(\"#pariwiseIframe,#breadcrumb\").show();\r\n");
      out.write("\t\t\t$(obj).parent().next().removeClass(\"current-menu-item\");\r\n");
      out.write("\t\t\t$(obj).parent().addClass(\"current-menu-item\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tvar typeID = \"\";\r\n");
      out.write("\tfunction MyModal(str,type){\r\n");
      out.write("\t\t$(\"#selectFileModal\").modal(str);\r\n");
      out.write("\t\tif(str == 'show'){\r\n");
      out.write("\t\t\t$(\"#file\").attr(\"flag\",type);\r\n");
      out.write("\t\t\t$(\"#okUpload\").attr(\"flag\",type);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ttypeID = type;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction MyModalTip(str){\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#tipInfo1\").html(str);\r\n");
      out.write("\t\t\t$(\"#tipModal1\").modal({backdrop: 'static', keyboard: false});\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction skipModalTip(str){\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#skipTipLabel\").html(str);\r\n");
      out.write("\t\t$(\"#skipModal\").modal({backdrop: 'static', keyboard: false});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction ModalTipLoading(str){\r\n");
      out.write("\t\tif(str=='hide'){\r\n");
      out.write("\t\t\t$(\"#tipModalLoading\").modal(str);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#tipModalLoading\").show();\r\n");
      out.write("\t\t\t$(\"#tipModalLoading\").modal({backdrop: 'static', keyboard: false});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction MyModalFormatTip(id){\r\n");
      out.write("\t\t$(\"#formatHid\").val(id);\r\n");
      out.write("\t\t$(\"#tipformatModal\").modal({backdrop: 'static', keyboard: false});\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction submitUploadFile(){\r\n");
      out.write("\t\tcheck();\r\n");
      out.write("\t}\r\n");
      out.write("    function check() {\r\n");
      out.write("        var f = document.getElementById(\"file\").files;\r\n");
      out.write("\t\tfor(var i=0;i<f.length;i++){\r\n");
      out.write("\t\t\tif(f[i].size>1*1024*1024){\r\n");
      out.write("\t\t\t\tvar tipInfo111 = f[0].name +\" file is too large!Less than 1 MB file please upload again!\";\r\n");
      out.write("\t\t\t\tshowTip(tipInfo111);\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar filename = $(\"#file\").val();\r\n");
      out.write(" \t\tif(filename.endWith(\".graphml\")||filename.endWith(\".gml\")||filename.endWith(\".edgelist\")){\r\n");
      out.write("\t\t\tvar type = $(\"#okUpload\").attr(\"flag\");\r\n");
      out.write("\t\t\t$(\"#pariwiseIframe\")[0].contentWindow.submitUploadFile(type);\r\n");
      out.write("\t\t\t//$(\"#file\").attr(\"flag\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar showname = f[0].name.substring(0,f[0].name.indexOf(\".\"));\r\n");
      out.write("\t\t\t$(\"#fileName\"+$(\"#file\").attr(\"flag\"),window.frames['pariwiseIframe'].document).val(f[0].name);\r\n");
      out.write("\t\t\tif(showname.length>10){\r\n");
      out.write("\t\t\t\t$(\"#selectFileWidth\"+$(\"#file\").attr(\"flag\"),window.frames['pariwiseIframe'].document).css(\"width\",\"200px\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif(showname.length>=20){\r\n");
      out.write("\t\t\t\t\tshowname = showname.substring(0,17)+\"…\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\"#selectFile\"+$(\"#file\").attr(\"flag\"),window.frames['pariwiseIframe'].document).text(showname);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tshowTip(\"File upload error format!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("    }\r\n");
      out.write("\tfunction showTip(info){\r\n");
      out.write("\r\n");
      out.write("\t\twindow.parent.window.MyModalTip(info);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t String.prototype.endWith=function(s){\r\n");
      out.write("\t\t  if(s==null||s==\"\"||this.length==0||s.length>this.length)\r\n");
      out.write("\t\t     return false;\r\n");
      out.write("\t\t  if(this.substring(this.length-s.length)==s)\r\n");
      out.write("\t\t     return true;\r\n");
      out.write("\t\t  else\r\n");
      out.write("\t\t     return false;\r\n");
      out.write("\t\t  return true;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction startIntro(){\r\n");
      out.write("\t\tdocument.getElementById('pariwiseIframe').contentWindow.startIntro();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction formatOK(){\r\n");
      out.write("\t\tvar id = $(\"#formatHid\").val();\r\n");
      out.write("\t\tvar txt = $(\"#textareaNet\"+id,window.frames['pariwiseIframe'].document).val();\r\n");
      out.write("\t\tvar select = $(\"#formatType\").val();\r\n");
      out.write("\t\tvar idType = $(\"#idTypeUploadformat\").val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t \t   type: \"POST\",\r\n");
      out.write("\t\t \t   async: true,\r\n");
      out.write("\t\t \t   data:{content:txt,type:select,id:id,idType:idType},\r\n");
      out.write("\t\t \t   url: \"networksimilarity/formatChange.form\",\r\n");
      out.write("\t\t \t   success: function(msg){\r\n");
      out.write("\t\t \t       var result = JSON.parse(msg);\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \t       var data = result.data;\r\n");
      out.write("\t\t \t       if(data == 'success'){\r\n");
      out.write("\r\n");
      out.write("\t\t \t    \t   var num = result.result;\r\n");
      out.write("\t\t \t    \t   var node = result.node;\r\n");
      out.write("\t\t \t    \t $(\"#fileName\"+id,window.frames['pariwiseIframe'].document).val(\"Input\"+id+\".\"+select);\r\n");
      out.write("\t\t \t    \t   if(num == -9999){\r\n");
      out.write("\t\t \t    \t\t   showTip(\"The \"+idType+\" mistakes!\");\r\n");
      out.write("\t\t \t    \t   }else {\r\n");
      out.write("\t\t \t    \t\t   $(\"#tipXBtn\").hide();\r\n");
      out.write("\t\t \t    \t\t   $(\"#tipCancelBtn\").show();\r\n");
      out.write("\t\t \t    \t\t   $(\"#tipCancelBtn\").bind(\"click\",function(){\r\n");
      out.write("\t\t \t    \t\t\t   $(\"#textareaNet\" + id).val(\"\");\r\n");
      out.write("\t\t \t    \t\t\t   $(\"#previewNet\" + id).html(\"A preview of your query network will show here\");\r\n");
      out.write("\t\t \t    \t\t\t   $(\"#hiddenTxt\" + id).html(\"0\");\r\n");
      out.write("\t\t \t    \t\t   });\r\n");
      out.write("\t\t \t    \t\t   $(window.parent.document.getElementById(\"tipOKBtn\")).bind(\"click\",function(){\r\n");
      out.write("\t\t \t    \t\t\t  $(\"#pariwiseIframe\")[0].contentWindow.showNetAllInfo(id);\r\n");
      out.write("\t\t \t    \t\t   });\r\n");
      out.write("\t \t    \t\t \t\t   \r\n");
      out.write("\t\t \t    \t\t  $(\"#pariwiseIframe\",parent.document).css(\"height\",($(\"#pariwiseIframe\",parent.document).height()+40)+\"px\");\r\n");
      out.write("\t\t \t    \t\t   var table=\"\";\r\n");
      out.write("\t\t \t    \t\t   console.log(result.error);\r\n");
      out.write("\t\t \t    \t\t   for(var dd in result.error){\r\n");
      out.write("\t\t \t    \t\t\t   table += \"<tr><td>\"+result.error[dd]+\"</td><td>\"+dd+\"</td></tr>\";\r\n");
      out.write("\t\t \t    \t\t   }\r\n");
      out.write("\t\t \t    \t\t   showTip(\r\n");
      out.write("\t\t \t    \t\t\t\t   \"In the gene identifiers you provided:<br>\"+\r\n");
      out.write("\t\t \t    \t\t\t\t   +node + \" matched to human genes,<br><a href='javascript:void(0)' style='cursor: pointer;' title=\\\"Check the details\\\" onclick='return $(\\\"#errorDiv\\\").show()'>\"\r\n");
      out.write("\t\t \t    \t\t\t\t   +num + \"</a> did not match to any human genes.<br>\"+\r\n");
      out.write("\t\t \t    \t\t\t\t   \"Make sure that you have selected the correct networks.<br><br><b><center>continue?</center><b>\"\r\n");
      out.write("\t\t \t    \t\t\t\t   +\"<br>\" +\r\n");
      out.write("\t\t \t    \t\t\t\t   \"<div id='errorDiv' style='display:none'><p style='margin-left:10px;'>not match info</p><div  style='width:100%;overflow: auto;border-top:1px solid;border-bottom:1px solid;    border-color: #67c2ef;'><table><tr><td>id</td><td>data</td></tr></table></div><div style='width:100%;height:200px;overflow: auto;border-bottom:1px solid;border-color: #67c2ef;'><table>\"+table+\"</table></div></div>\");\r\n");
      out.write("\t\t \t    \r\n");
      out.write("\t\t \t    \t\t   \r\n");
      out.write(" \t\t\t\t\t/* \tshowTip(\"In the gene identifiers you provided:<br>\"\r\n");
      out.write("\t\t \t    \t\t\t\t+node + \" matched to human genes,<br>\"\r\n");
      out.write("\t\t \t    \t\t\t\t+num + \" did not match to any human genes.<br>\"\r\n");
      out.write("\t\t \t    \t\t\t\t+\"Make sure that you have selected the correct networks.<br><br><b><center>continue?</center><b>\"\r\n");
      out.write("\t\t \t    \t\t\t\t\t\t\t\t\t\t\t); */\r\n");
      out.write("\t\t \t    \t   }\r\n");
      out.write("\t\t \t       }else if(data == 'error'){\r\n");
      out.write("\t\t\t\t    \t  showTip(\"Format or input errors!\");\r\n");
      out.write("\t\t\t\t      }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/views/rweb/networksimilarity/networksimilarityAnalysis.jsp(138,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a id=\"resource1\" href=\"networksimilaritystatistical\">Statistics of current release</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a id=\"resource2\" href=\"networksimilarityprofiles\">My Profiles</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }
}
