/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-12-29 02:34:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.rweb.networksimilarity;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class networksimilarityNews_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \t<meta charset=\"utf-8\">\r\n");
      out.write("\t    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t    <title>Network Fingerprint Scanner</title>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Fav and touch icons -->\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"static/image/w1.png\" />\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css\">\t\t\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/style.css\" rel=\"stylesheet\" type=\"text/css\">\t\r\n");
      out.write("\t\t<link href=\"rweb/css/header.css\"  type=\"text/css\" rel=\"stylesheet\">\t\r\n");
      out.write("<!-- \t\t<link href=\"static/css/release.css\"  type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write(" -->\t\t<script>\r\n");
      out.write("\t\t\tif (navigator.userAgent.split(\";\")[1].toLowerCase().indexOf(\"msie\") > 0 ){\r\n");
      out.write("\t\t\t\twindow.location.href = \"supportInfo\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t.login-box,\r\n");
      out.write("\t\t\t.register-box {\r\n");
      out.write("\t\t\t  width: 400px;\r\n");
      out.write("\t\t\t  padding: 20px;\r\n");
      out.write("\t\t\t  margin: 110px auto;\r\n");
      out.write("\t\t\t  background: #fff;\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\t.login-box .header,\r\n");
      out.write("\t\t\t.register-box .header {\r\n");
      out.write("\t\t\t  background: #414141;\r\n");
      out.write("\t\t\t  color: white;\r\n");
      out.write("\t\t\t  text-align: center;\r\n");
      out.write("\t\t\t  margin: -20px -20px 20px -20px;\r\n");
      out.write("\t\t\t  padding: 15px;\r\n");
      out.write("\t\t\t  text-transform: uppercase;\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\t.login-box .text-center li {\r\n");
      out.write("\t\t\t  display: inline-block;  \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.login-box .text-center li a {\r\n");
      out.write("\t\t\t  width: 45px;\r\n");
      out.write("\t\t\t  height: 45px;\r\n");
      out.write("\t\t\t  text-decoration: none;\r\n");
      out.write("\t\t\t  padding-top: 13px;\r\n");
      out.write("\t\t\t  font-size: 23px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.login-box .text-center li a:hover {\r\n");
      out.write("\t\t\t  color: #fff;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.login-box label,\r\n");
      out.write("\t\t\t.register-box label {\r\n");
      out.write("\t\t\t  margin: 10px 5px -10px 5px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.login-box .confirm,\r\n");
      out.write("\t\t\t.register-box .confirm {\r\n");
      out.write("\t\t\t  position: relative;\r\n");
      out.write("\t\t\t  margin: 20px 0 10px -15px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.login-box .confirm label,\r\n");
      out.write("\t\t\t.register-box .confirm label {\r\n");
      out.write("\t\t\t  position: absolute;\r\n");
      out.write("\t\t\t  top: -9px;\r\n");
      out.write("\t\t\t  left: 30px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.login-box form.register .input-group-addon,\r\n");
      out.write("\t\t\t.register-box form.register .input-group-addon {\r\n");
      out.write("\t\t\t  width: 35%;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t/* ydj */\r\n");
      out.write("\t\t\t.action-item {\r\n");
      out.write("\t\t\t    display: inline-block;\r\n");
      out.write("\t\t\t    padding-right: .5rem;\r\n");
      out.write("\t\t\t    padding-left: .25rem;\r\n");
      out.write("\t\t\t    border-right-width: 1px;\r\n");
      out.write("\t\t\t    border-right-style: solid;\r\n");
      out.write("\t\t\t\t    line-height: 1.25rem;\r\n");
      out.write("\t\t\t    font-size: 1rem;\r\n");
      out.write("\t\t\t    color: #999;\r\n");
      out.write("\t\t\t    text-transform: uppercase;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.action-item a{\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.radio-inline, .checkbox-inline{\r\n");
      out.write("\t\t\t\tline-height:22px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.btn1 {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tmargin-bottom: 0;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground-image: none;\r\n");
      out.write("\tborder: 1px solid transparent;\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("\tpadding: 6px 12px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tline-height: 1.42857143;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\t-webkit-user-select: none;\r\n");
      out.write("\t-moz-user-select: none;\r\n");
      out.write("\t-ms-user-select: none;\r\n");
      out.write("\tuser-select: none\r\n");
      out.write("}\r\n");
      out.write(".contactContent {\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    margin-left: 10px;\r\n");
      out.write("    /* margin-right: 10px; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fieldWrapper #hint {\r\n");
      out.write("    margin-left: 10px;\r\n");
      out.write("    opacity: 0.5;\r\n");
      out.write("}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"font-size:medium; line-height: 1.5em\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<!-- Header -->\r\n");
      out.write("\t\t\t<header id=\"\" class=\"sticky-header\" style=\"opacity: 1;padding:0;\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Main Header -->\r\n");
      out.write("\t\t\t\t<div id=\"main-header\" style=\"height: 80px;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"logo\" class=\"col-lg-12 col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"static/image/b2.png\" style=\"width: 110px;margin-top: -20px;margin-right: -20px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<span style=\"color:white;font-size:33px;margin-top: 1px;\">Network Fingerprint Scanner</span> \r\n");
      out.write("\t\t\t\t\t\t\t<span style=\"color: white; font-size: 15px; top: 28px; margin-left: 5px;\">NFPscanner:a server for knowledge-based characterization of biomedical networks\r\n");
      out.write("</span> <span style=\"position:absolute;right:10;top:6;display: none;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          //  c:when
          org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
          _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
          _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          // /WEB-INF/views/rweb/networksimilarity/networksimilarityNews.jsp(142,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
          int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
          if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"btn-user\"><i class=\"fa fa-user\"></i> ");
              out.print(session.getAttribute("username") );
              out.write("</button>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"logout()\" id=\"btn-out\"><i class=\"fa  fa-user-md\"></i> Log Out</button>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
            return;
          }
          _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /Main Header -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Lower Header -->\r\n");
      out.write("\t\t\t\t<div id=\"lower-header\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"menu-button\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span>Menu</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul id=\"navigation\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- Home -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"current-menu-item\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa \" href=\"networksimilarityHome.html\">Home</a>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- /home -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- Events -->\r\n");
      out.write("\t\t\t\t\t\t<li  style=\"width: 300px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityAnalysis?type=1\">Network Fingerprint Scan</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"width: 250px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityAnalysis?type=2\">Pairwise Alignment</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- /Events -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- Media -->\r\n");
      out.write("\t\t\t\t\t\t<!-- /Media -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- Features -->\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa \" href=\"networksimilaritystatistical\">Resource</a>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- /Features -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- Get Involved -->\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityHelp\">Help</a>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- /Get Involved -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- CONTACT -->\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityContact\">Contact</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- /CONTACT -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /Lower Header -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t<!-- /Header -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- /Header -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Section -->\r\n");
      out.write("\t\t\t<section class=\"section full-width-bg\" style=\"padding-top:20px;height:100%;\">\r\n");
      out.write("\t\t<div class=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"legacyTitle\" style=\"margin-left: 15px;margin-top: 10px;\">Version 1.4 online</div>\r\n");
      out.write("\t\t\t<div class=\"legacyContent\">\r\n");
      out.write("\t\t\t\t<div class=\"legacyDate\" style=\"margin-left: 15px;\">10th November 2015</div>\r\n");
      out.write("\t\t\t\t<div class=\"legacyDes\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<span >\r\n");
      out.write("\t\t\t\t\t\t\tServer web interface and help page is updated.\r\n");
      out.write(" </span> \r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"legacyTitle\" style=\"margin-left: 15px;margin-top: 10px;\">Version 1.3 online</div>\r\n");
      out.write("\t\t\t<div class=\"legacyContent\">\r\n");
      out.write("\t\t\t\t<div class=\"legacyDate\" style=\"margin-left: 15px;\">10th November 2015</div>\r\n");
      out.write("\t\t\t\t<div class=\"legacyDes\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\tExample data are deployed. Step-by-step tutorial guide are implemented. \r\n");
      out.write("\t\t\t\t\t\t </span> \r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"legacyTitle\" style=\"margin-left: 15px;margin-top: 10px;\">Version 1.2 online</div>\r\n");
      out.write("\t\t\t<div class=\"legacyContent\">\r\n");
      out.write("\t\t\t\t<div class=\"legacyDate\" style=\"margin-left: 15px;\">1st November 2015</div>\r\n");
      out.write("\t\t\t\t<div class=\"legacyDes\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\tAlternative basic networks are added and organized as public resource of NFPscanner server. \r\n");
      out.write("\t\t\t\t\t\t </span> \r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"legacyTitle\" style=\"margin-left: 15px;margin-top: 10px;\">Version 1.1 online</div>\r\n");
      out.write("\t\t\t<div class=\"legacyContent\">\r\n");
      out.write("\t\t\t\t<div class=\"legacyDate\" style=\"margin-left: 15px;\">15th October 2015</div>\r\n");
      out.write("\t\t\t\t<div class=\"legacyDes\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<span >\r\n");
      out.write("\t\t\t\t\t\t\tPairwise alignment service, IsoRank algorithm, SPINAL algorithm, GHOST algorithm are added. \r\n");
      out.write("\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"legacyTitle\" style=\"margin-left: 15px;margin-top: 10px;\">Version 1.0 online</div>\r\n");
      out.write("\t\t\t<div class=\"legacyContent\">\r\n");
      out.write("\t\t\t\t<div class=\"legacyDate\" style=\"margin-left: 15px;\">1st October 2015</div>\r\n");
      out.write("\t\t\t\t<div class=\"legacyDes\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<span >\r\n");
      out.write("\t\t\t\t\t\t\tThe APcluster algorithm and KEGG basic networks are implemented.  </span> \r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t<!-- /Section -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<footer id=\"footer1\" >\t\r\n");
      out.write("\t\t\t\t<!-- Lower Footer -->\r\n");
      out.write("\t\t\t\t<div id=\"lower-footer\" >\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-4\" style=\"opacity: 1;width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div align=\"center\">\r\n");
      out.write(" \t\t\t\t\t\t\t\t <p class=\"copyright\">NFPscanner is supported by a grant from National Nature Science Foundation of China.\r\n");
      out.write("\t\t\t\t\t\t\t\t </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t <p class=\"copyright\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Copyright © 2015-2016 Beijing Institute of Radiation Medicine</p>\r\n");
      out.write(" \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /Lower Footer -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<script src=\"http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.1.min.js\"></script>\r\n");
      out.write(" \t<script src=\"//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"static/js/networksimilarityContact.js\"></script>\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tfunction startIntro(){\r\n");
      out.write("\t\tdocument.getElementById('pariwiseIframe').contentWindow.startIntro();\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"btn-login\" data-toggle=\"modal\" data-target=\"#loginModal\"><i class=\"fa fa-lightbulb-o\"></i> Login</button>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"btn-signup\" data-toggle=\"modal\" data-target=\"#signupModal\"><i class=\"fa  fa-user-md\"></i> Sign Up</button>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f1.setParent(null);
    int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
    if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    // /WEB-INF/views/rweb/networksimilarity/networksimilarityNews.jsp(204,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
    if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a id=\"resource1\" href=\"networksimilaritystatistical\">Statistics of current release</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a id=\"resource2\" href=\"networksimilarityprofiles\">My Profiles</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
    return false;
  }
}
