/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-12-29 02:53:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.rweb.networksimilarity;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class networksimilarityHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Network Fingerprint Scanning</title>\r\n");
      out.write("\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!-- Favicon -->\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"static/image/w1.png\" />\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<!-- ydj -->\r\n");
      out.write("\t\t<link href=\"rweb/css/header.css\"  type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tif (navigator.userAgent.split(\";\")[1].toLowerCase().indexOf(\"msie\") > 0 ){\r\n");
      out.write("\t\t\t\twindow.location.href = \"supportInfo\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<!-- jQuery -->\r\n");
      out.write("\t\t\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write(" <body class=\"sticky-header-on tablet-sticky-header\" style=\"padding-bottom:0;\tfont-size:medium\r\n");
      out.write("; line-height: 1.5em\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"fb-root\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Container -->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Header -->\r\n");
      out.write("\t\t\t<header id=\"\" class=\"sticky-header\" style=\"opacity: 1;padding:0;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Main Header -->\r\n");
      out.write("\t\t\t\t<div id=\"main-header\" style=\"height: 80px;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"logo\" class=\"col-lg-12 col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"static/image/b2.png\" style=\"width: 110px;margin-top: -20px;margin-right: -20px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<span style=\"color:white;font-size:33px;margin-top: 1px;\">Network Fingerprint Scanner</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span style=\"color: white; font-size: 15px; top: 28px; margin-left: 5px;\">NFPscanner:a server for knowledge-based characterization of biomedical networks\r\n");
      out.write("</span> ");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /Main Header -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Lower Header -->\r\n");
      out.write("\t\t\t\t<div id=\"lower-header\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"menu-button\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span>Menu</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul id=\"navigation\" style=\"\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Home -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"current-menu-item\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa \" href=\"networksimilarityHome\">Home</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- /home -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Events -->\r\n");
      out.write("\t\t\t\t\t\t<li  style=\"width: 300px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityAnalysis?type=1\">Network Fingerprint Scan</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"width: 250px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityAnalysis?type=2\">Pairwise Alignment</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- /Events -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Media -->\r\n");
      out.write("\t\t\t\t\t\t<!-- /Media -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Features -->\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa \" href=\"networksimilaritystatistical\">Resource</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- /Features -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Get Involved -->\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityHelp\">Help</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- /Get Involved -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- CONTACT -->\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityContact\">Contact</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- /CONTACT -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /Lower Header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t<!-- /Header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<section id=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Section -->\r\n");
      out.write("\t\t\t<section class=\"section full-width-bg\" style=\"padding-top:20px\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t<h3 style=\"text-align:center\">Welcome to NFPscanner</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"intro\">\r\n");
      out.write("\t\t\t\t\t \t<p style=\"line-height:1.5em\">\r\n");
      out.write("Network Fingerprint Scanner (NFPscanner) is a web server to decipher biomedical networks by making systematic comparisons to well-studied basic networks. A given biomedical network is characterized as a spectrum-like vector called “network fingerprint”, which contains similarities to basic networks. The similarity is measured by conservations of protein-protein interactions (PPI), sequence and functional annotations. This knowledge-based multidimensional characterization provides an intuitive way to decipher molecular networks, especially for large-scale network comparison and clustering analyses. <br/>\r\n");
      out.write("The NFPscanner has three highlighted features:<br/>\r\n");
      out.write("<ol>\r\n");
      out.write("\t<li>\r\n");
      out.write("Incorporation of 4 network alignment algorithms (\r\n");
      out.write("<a href=\"networksimilarityHelp#APcluster\">APcluster</a>,  \r\n");
      out.write("<a href=\"networksimilarityHelp#IsoRankN\">IsoRankN</a>, \r\n");
      out.write("<a href=\"networksimilarityHelp#SPINAL\">SPINAL</a>, \r\n");
      out.write("<a href=\"networksimilarityHelp#GHOST\">GHOST</a>);\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li>\r\n");
      out.write("Manually curated 49 sets of basic networks, retrieved from 6 network databases (\r\n");
      out.write("<a href=\"http://www.genome.jp/kegg/\">KEGG</a>,  \r\n");
      out.write("<a href=\"http://www.reactome.org/\">Reactome</a>,  \r\n");
      out.write("<a href=\"http://pid.nci.nih.gov/\">NCI/PID</a>,  \r\n");
      out.write("<a href=\"http://www.cs.tau.ac.il/~spike/\">SPIKE</a>,  \r\n");
      out.write("<a href=\"http://humancyc.org/\">HumanCyc</a>,  \r\n");
      out.write("<a href=\"http://pantherdb.org/\">PANTHER</a>,\r\n");
      out.write("<a href=\"http://cgap.nci.nih.gov/Pathways/BioCarta_Pathways/\">BioCarta</a>\r\n");
      out.write(");\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li>\r\n");
      out.write("Visualization of \r\n");
      out.write("<a href=\"networksimilarityHelp#UnderstandbodyA\">network fingerprint </a>\r\n");
      out.write("and \r\n");
      out.write("<a href=\"networksimilarityHelp#ExplorebodyA\">pairwise alignment </a>.<br/>\r\n");
      out.write("\t</li>\r\n");
      out.write("</ol>\r\n");
      out.write("You are always welcome to improve NFPscanner service by commenting, contribute alignment algorithms and/or special basic network sets. Feel free to \r\n");
      out.write("<a href=\"networksimilarityContact\">contact us</a>\r\n");
      out.write("if you have any comments or questions on this web server.\r\n");
      out.write("\t\t\t\t\t \t</p>\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t<img src='static/image/home1.jpg'/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-4 sidebar\" style=\"padding-right:15px;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sidebar-box white \" style=\"opacity: 1;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Quick Start </h3>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>New to NFPscanner? Try the tutorials now.</h4>\r\n");
      out.write("             \t\t\t\t <a href=\"javascript:void(0);\" onclick=\"playtour(1)\" class=\"btn btn-primary\" style=\"margin-bottom:0.5em\"><span class=\"glyphicon glyphicon-play\" aria-hidden=\"true\"></span>&nbsp;Tutorial for Fingerprint Scan</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:void(0);\" onclick=\"playtour(2)\" class=\"btn btn-primary\" ><span class=\"glyphicon glyphicon-play \" aria-hidden=\"true\"></span>&nbsp;Tutorial for Pairwise Alignment</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- /Featured Video -->\r\n");
      out.write("\t\t\t\t\t\t<!-- Featured Video -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sidebar-box white\" style=\"opacity: 1;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Statistics</h3>\r\n");
      out.write("              <h4>NFPscanner webserver contains:</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 style=\"display:inline\"> 2 </h4> analysis tools <br>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 style=\"display:inline\"> 4 </h4> alignment algorithms<br>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 style=\"display:inline\"> 49 </h4> set of basic networks from <h4 style=\"display:inline\"> 7 </h4> databases\r\n");
      out.write("              </p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /Featured Video -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Upcoming Events -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sidebar-box white\" style=\"opacity: 1;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>What’s New?</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"upcoming-events\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Event -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"event-content\">\r\n");
      out.write("                    <h4><a href=\"networksimilarityNews\">Version 1.4 online. </a></h4>\r\n");
      out.write("                    <ul class=\"event-meta\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"icons icon-clock\"></i>30th November 2015</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("                    Server web interface and help page is updated.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"event-content\">\r\n");
      out.write("                    <h4><a href=\"networksimilarityNews\"> Version 1.3 online.</a></h4>\r\n");
      out.write("                    <ul class=\"event-meta\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"icons icon-clock\"></i>10th November 2015</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("                     Example data are deployed. Step-by-step tutorial guides are implemented. \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /Event -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"networksimilarityNews\" class=\"button transparent button-arrow\">More events</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<!-- /Section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Footer -->\r\n");
      out.write("\t\t\t<footer id=\"footer1\" >\r\n");
      out.write("\t\t\t\t<!-- Lower Footer -->\r\n");
      out.write("\t\t\t\t<div id=\"lower-footer\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-left: 98%\">\t\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\" src=\"//ra.revolvermaps.com/0/0/3.js?i=0eu6839u0la&amp;b=0&amp;s=26&amp;m=2&amp;cl=ffffff&amp;co=010020&amp;cd=aa0000&amp;v0=60&amp;v1=60&amp;r=1\" async=\"async\"></script>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-4\" style=\"opacity: 1;width: 100%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div align=\"center\">\r\n");
      out.write(" \t\t\t\t\t\t\t\t <p class=\"copyright\">NFPscanner is supported by a grant from National Nature Science Foundation of China.\r\n");
      out.write("\t\t\t\t\t\t\t\t </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t <p class=\"copyright\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Copyright © 2015-2016 Beijing Institute of Radiation Medicine</p>\r\n");
      out.write(" \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /Lower Footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\t\t<!-- /Footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Back To Top -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /Container -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- JavaScript -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Bootstrap -->\r\n");
      out.write("\t\t<script src=\"http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction playtour(type){\r\n");
      out.write("\t\t\tsetCookie(\"play\",type);\r\n");
      out.write("\t\t\twindow.location.href = \"networksimilarityAnalysis?type=\" + type + \"&play=\" + type;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction setCookie(name,value) \r\n");
      out.write("\t\t{ \r\n");
      out.write("\t\t\tvar Days = 30; \r\n");
      out.write("\t\t\tvar exp = new Date(); \r\n");
      out.write("\t\t\texp.setTime(exp.getTime() + Days*24*60*60*1000); \r\n");
      out.write("\t\t\tdocument.cookie = name + \"=\"+ escape (value) + \";expires=\" + exp.toGMTString(); \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
