/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-12-31 06:53:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.rweb.networksimilarity;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class networksimilarityHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("    <title>Network Fingerprint Scanning</title>\r\n");
      out.write("\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!-- Favicon -->\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"static/image/w1.png\" />\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/climacons-font.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<!-- Stylesheets -->\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/fontello.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/flexslider.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/owl.carousel.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<link href=\"rweb/css/comment.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<!-- ydj -->\r\n");
      out.write("\t\t<link href=\"rweb/css/header.css\"  type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t\t<link href=\"static/css/help.css\"  type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tif (navigator.userAgent.split(\";\")[1].toLowerCase().indexOf(\"msie\") > 0 ){\r\n");
      out.write("\t\t\t\talert(\"A problem with your browser\\n You are using a very old version of Internet Explorer.\\n We recommend you upgrade to an alternative browser than Internet Explorer.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\t.login-box,\r\n");
      out.write("\t\t\t.register-box {\r\n");
      out.write("\t\t\t  width: 400px;\r\n");
      out.write("\t\t\t  padding: 20px;\r\n");
      out.write("\t\t\t  margin: 110px auto;\r\n");
      out.write("\t\t\t  background: #fff;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.login-box .header,\r\n");
      out.write("\t\t\t.register-box .header {\r\n");
      out.write("\t\t\t  background: #414141;\r\n");
      out.write("\t\t\t  color: white;\r\n");
      out.write("\t\t\t  text-align: center;\r\n");
      out.write("\t\t\t  margin: -20px -20px 20px -20px;\r\n");
      out.write("\t\t\t  padding: 15px;\r\n");
      out.write("\t\t\t  text-transform: uppercase;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.login-box .text-center li {\r\n");
      out.write("\t\t\t  display: inline-block;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.login-box .text-center li a {\r\n");
      out.write("\t\t\t  width: 45px;\r\n");
      out.write("\t\t\t  height: 45px;\r\n");
      out.write("\t\t\t  text-decoration: none;\r\n");
      out.write("\t\t\t  padding-top: 13px;\r\n");
      out.write("\t\t\t  font-size: 23px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.login-box .text-center li a:hover {\r\n");
      out.write("\t\t\t  color: #fff;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.login-box label,\r\n");
      out.write("\t\t\t.register-box label {\r\n");
      out.write("\t\t\t  margin: 10px 5px -10px 5px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.login-box .confirm,\r\n");
      out.write("\t\t\t.register-box .confirm {\r\n");
      out.write("\t\t\t  position: relative;\r\n");
      out.write("\t\t\t  margin: 20px 0 10px -15px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.login-box .confirm label,\r\n");
      out.write("\t\t\t.register-box .confirm label {\r\n");
      out.write("\t\t\t  position: absolute;\r\n");
      out.write("\t\t\t  top: -9px;\r\n");
      out.write("\t\t\t  left: 30px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.login-box form.register .input-group-addon,\r\n");
      out.write("\t\t\t.register-box form.register .input-group-addon {\r\n");
      out.write("\t\t\t  width: 35%;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t/* ydj */\r\n");
      out.write("\t\t\t.btn\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdisplay:inline-block;\r\n");
      out.write("\t\t\t\ttext-transform: none;\r\n");
      out.write("\t\t\t\tmargin-bottom:0;\r\n");
      out.write("\t\t\t\tfont-family:\"Helvetica Neue\",Helvetica,Tahoma,Arial,sans-serif;\r\n");
      out.write("\t\t\t\tfont-size:14px;\r\n");
      out.write("\t\t\t\tfont-weight:400;\r\n");
      out.write("\t\t\t\tline-height:1.42857143;\r\n");
      out.write("\t\t\t\ttext-align:center;\r\n");
      out.write("\t\t\t\twhite-space:nowrap;\r\n");
      out.write("\t\t\t\tvertical-align:middle;\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\t-webkit-user-select:none;\r\n");
      out.write("\t\t\t\t-moz-user-select:none;\r\n");
      out.write("\t\t\t\t-ms-user-select:none;\r\n");
      out.write("\t\t\t\tuser-select:none;\r\n");
      out.write("\t\t\t\tbackground-image:none;\r\n");
      out.write("\t\t\t\tborder:1px solid transparent;\r\n");
      out.write("\t\t\t\tborder-radius:2px;\r\n");
      out.write("\t\t\t\t-webkit-transition:all .8s cubic-bezier(.175,.885,.32,1);\r\n");
      out.write("\t\t\t\t-o-transition:all .8s cubic-bezier(.175,.885,.32,1);\r\n");
      out.write("\t\t\t\ttransition:all .8s cubic-bezier(.175,.885,.32,1);\r\n");
      out.write("\t\t\t\tcolor:#141414;\r\n");
      out.write("\t\t\t\ttext-shadow:0 1px 0 #fff;\r\n");
      out.write("\t\t\t\tbackground-color:#f0f0f0;\r\n");
      out.write("\t\t\t\tborder-color:#ccc;\r\n");
      out.write("\t\t\t\tpadding:6px 12px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn:hover,.btn:focus\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcolor:#141414;\r\n");
      out.write("\t\t\t\ttext-decoration:none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn:active,.btn.active\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tbackground-image:none;\r\n");
      out.write("\t\t\t\toutline:0;\r\n");
      out.write("\t\t\t\t-webkit-box-shadow:inset 0 3px 5px rgba(0,0,0,.125);\r\n");
      out.write("\t\t\t\tbox-shadow:inset 0 3px 5px rgba(0,0,0,.125);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn.disabled,.btn[disabled],fieldset[disabled] .btn\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tpointer-events:none;\r\n");
      out.write("\t\t\t\tcursor:not-allowed;\r\n");
      out.write("\t\t\t\tfilter:alpha(opacity=65);\r\n");
      out.write("\t\t\t\t-webkit-box-shadow:none;\r\n");
      out.write("\t\t\t\tbox-shadow:none;\r\n");
      out.write("\t\t\t\topacity:.65;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn:hover,.btn:focus,.btn:active,.btn.active,.open .dropdown-toggle.btn\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcolor:#141414;\r\n");
      out.write("\t\t\t\tbackground-color:#dbdbdb;\r\n");
      out.write("\t\t\t\t-webkit-box-shadow:0 2px 1px rgba(0,0,0,.1);\r\n");
      out.write("\t\t\t\tbox-shadow:0 2px 1px rgba(0,0,0,.1);\r\n");
      out.write("\t\t\t\tborder-color:#9e9e9e;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn.disabled,.btn[disabled],fieldset[disabled] .btn,.btn.disabled:hover,.btn[disabled]:hover,fieldset[disabled] .btn:hover,.btn.disabled:focus,.btn[disabled]:focus,fieldset[disabled] .btn:focus,.btn.disabled:active,.btn[disabled]:active,fieldset[disabled] .btn:active,.btn.disabled.active,.btn[disabled].active,fieldset[disabled] .btn.active\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tbackground-color:#f0f0f0;\r\n");
      out.write("\t\t\t\tborder-color:#bdbdbd;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-primary\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcolor:#fff;\r\n");
      out.write("\t\t\t\ttext-shadow:0 -1px 0 rgba(0,0,0,.2);\r\n");
      out.write("\t\t\t\tbackground-color:#1a4f85;\r\n");
      out.write("\t\t\t\tborder-color:#103152;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-primary:hover,.btn-primary:focus,.btn-primary:active,.btn-primary.active,.open .dropdown-toggle.btn-primary\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcolor:#fff;\r\n");
      out.write("\t\t\t\tbackground-color:#133b63;\r\n");
      out.write("\t\t\t\t-webkit-box-shadow:0 2px 1px rgba(0,0,0,.1);\r\n");
      out.write("\t\t\t\tbox-shadow:0 2px 1px rgba(0,0,0,.1);\r\n");
      out.write("\t\t\t\tborder-color:#0c243c;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-primary.disabled,.btn-primary[disabled],fieldset[disabled] .btn-primary,.btn-primary.disabled:hover,.btn-primary[disabled]:hover,fieldset[disabled] .btn-primary:hover,.btn-primary.disabled:focus,.btn-primary[disabled]:focus,fieldset[disabled] .btn-primary:focus,.btn-primary.disabled:active,.btn-primary[disabled]:active,fieldset[disabled] .btn-primary:active,.btn-primary.disabled.active,.btn-primary[disabled].active,fieldset[disabled] .btn-primary.active\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tbackground-color:#1a4f85;\r\n");
      out.write("\t\t\t\tborder-color:#164270;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-warning\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcolor:#fff;\r\n");
      out.write("\t\t\t\ttext-shadow:0 -1px 0 rgba(0,0,0,.2);\r\n");
      out.write("\t\t\t\tbackground-color:#e48600;\r\n");
      out.write("\t\t\t\tborder-color:#a76200;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-warning:hover,.btn-warning:focus,.btn-warning:active,.btn-warning.active,.open .dropdown-toggle.btn-warning\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcolor:#fff;\r\n");
      out.write("\t\t\t\tbackground-color:#bb6e00;\r\n");
      out.write("\t\t\t\t-webkit-box-shadow:0 2px 1px rgba(0,0,0,.1);\r\n");
      out.write("\t\t\t\tbox-shadow:0 2px 1px rgba(0,0,0,.1);\r\n");
      out.write("\t\t\t\tborder-color:#8d5300;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-warning.disabled,.btn-warning[disabled],fieldset[disabled] .btn-warning,.btn-warning.disabled:hover,.btn-warning[disabled]:hover,fieldset[disabled] .btn-warning:hover,.btn-warning.disabled:focus,.btn-warning[disabled]:focus,fieldset[disabled] .btn-warning:focus,.btn-warning.disabled:active,.btn-warning[disabled]:active,fieldset[disabled] .btn-warning:active,.btn-warning.disabled.active,.btn-warning[disabled].active,fieldset[disabled] .btn-warning.active\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tbackground-color:#e48600;\r\n");
      out.write("\t\t\t\tborder-color:#cb7700;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-danger\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcolor:#fff;\r\n");
      out.write("\t\t\t\ttext-shadow:0 -1px 0 rgba(0,0,0,.2);\r\n");
      out.write("\t\t\t\tbackground-color:#d2322d;\r\n");
      out.write("\t\t\t\tborder-color:#a02622;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-danger:hover,.btn-danger:focus,.btn-danger:active,.btn-danger.active,.open .dropdown-toggle.btn-danger\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcolor:#fff;\r\n");
      out.write("\t\t\t\tbackground-color:#b02a26;\r\n");
      out.write("\t\t\t\t-webkit-box-shadow:0 2px 1px rgba(0,0,0,.1);\r\n");
      out.write("\t\t\t\tbox-shadow:0 2px 1px rgba(0,0,0,.1);\r\n");
      out.write("\t\t\t\tborder-color:#8b211e;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-danger.disabled,.btn-danger[disabled],fieldset[disabled] .btn-danger,.btn-danger.disabled:hover,.btn-danger[disabled]:hover,fieldset[disabled] .btn-danger:hover,.btn-danger.disabled:focus,.btn-danger[disabled]:focus,fieldset[disabled] .btn-danger:focus,.btn-danger.disabled:active,.btn-danger[disabled]:active,fieldset[disabled] .btn-danger:active,.btn-danger.disabled.active,.btn-danger[disabled].active,fieldset[disabled] .btn-danger.active\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tbackground-color:#d2322d;\r\n");
      out.write("\t\t\t\tborder-color:#bd2d29;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-success\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcolor:#fff;\r\n");
      out.write("\t\t\t\ttext-shadow:0 -1px 0 rgba(0,0,0,.2);\r\n");
      out.write("\t\t\t\tbackground-color:#229f24;\r\n");
      out.write("\t\t\t\tborder-color:#176d19;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-success:hover,.btn-success:focus,.btn-success:active,.btn-success.active,.open .dropdown-toggle.btn-success\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcolor:#fff;\r\n");
      out.write("\t\t\t\tbackground-color:#1b7d1c;\r\n");
      out.write("\t\t\t\t-webkit-box-shadow:0 2px 1px rgba(0,0,0,.1);\r\n");
      out.write("\t\t\t\tbox-shadow:0 2px 1px rgba(0,0,0,.1);\r\n");
      out.write("\t\t\t\tborder-color:#135814;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-success.disabled,.btn-success[disabled],fieldset[disabled] .btn-success,.btn-success.disabled:hover,.btn-success[disabled]:hover,fieldset[disabled] .btn-success:hover,.btn-success.disabled:focus,.btn-success[disabled]:focus,fieldset[disabled] .btn-success:focus,.btn-success.disabled:active,.btn-success[disabled]:active,fieldset[disabled] .btn-success:active,.btn-success.disabled.active,.btn-success[disabled].active,fieldset[disabled] .btn-success.active\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tbackground-color:#229f24;\r\n");
      out.write("\t\t\t\tborder-color:#1e8a1f;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-info\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcolor:#fff;\r\n");
      out.write("\t\t\t\ttext-shadow:0 -1px 0 rgba(0,0,0,.2);\r\n");
      out.write("\t\t\t\tbackground-color:#39b3d7;\r\n");
      out.write("\t\t\t\tborder-color:#238faf;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-info:hover,.btn-info:focus,.btn-info:active,.btn-info.active,.open .dropdown-toggle.btn-info\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcolor:#fff;\r\n");
      out.write("\t\t\t\tbackground-color:#279dc0;\r\n");
      out.write("\t\t\t\t-webkit-box-shadow:0 2px 1px rgba(0,0,0,.1);\r\n");
      out.write("\t\t\t\tbox-shadow:0 2px 1px rgba(0,0,0,.1);\r\n");
      out.write("\t\t\t\tborder-color:#1f7e9a;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-info.disabled,.btn-info[disabled],fieldset[disabled] .btn-info,.btn-info.disabled:hover,.btn-info[disabled]:hover,fieldset[disabled] .btn-info:hover,.btn-info.disabled:focus,.btn-info[disabled]:focus,fieldset[disabled] .btn-info:focus,.btn-info.disabled:active,.btn-info[disabled]:active,fieldset[disabled] .btn-info:active,.btn-info.disabled.active,.btn-info[disabled].active,fieldset[disabled] .btn-info.active\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tbackground-color:#39b3d7;\r\n");
      out.write("\t\t\t\tborder-color:#29a8cd;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-link\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tfont-weight:400;\r\n");
      out.write("\t\t\t\tcolor:#03c;\r\n");
      out.write("\t\t\t\ttext-shadow:none;\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\tbackground:0;\r\n");
      out.write("\t\t\t\t-webkit-box-shadow:none;\r\n");
      out.write("\t\t\t\tbox-shadow:none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-link,.btn-link:active,.btn-link[disabled],fieldset[disabled] .btn-link,.btn-link:hover,.btn-link:focus\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t-webkit-box-shadow:none;\r\n");
      out.write("\t\t\t\tbox-shadow:none;\r\n");
      out.write("\t\t\t\tborder-color:transparent;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-link[disabled]:hover,fieldset[disabled] .btn-link:hover,.btn-link[disabled]:focus,fieldset[disabled] .btn-link:focus\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tcolor:#ddd;\r\n");
      out.write("\t\t\t\ttext-decoration:none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-xs,.btn-mini\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tpadding:1px 5px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-block\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdisplay:block;\r\n");
      out.write("\t\t\t\twidth:100%;\r\n");
      out.write("\t\t\t\tpadding-right:0;\r\n");
      out.write("\t\t\t\tpadding-left:0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-lg .caret\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tborder-width:5px 5px 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.dropup .btn-lg .caret\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tborder-width:0 5px 5px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-default .caret\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tborder-top-color:#141414;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.dropup .btn-default .caret\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tborder-bottom-color:#141414;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.dropup .btn-primary .caret,.dropup .btn-success .caret,.dropup .btn-warning .caret,.dropup .btn-danger .caret,.dropup .btn-info .caret\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tborder-bottom-color:#fff;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-group,.btn-group-vertical\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tposition:relative;\r\n");
      out.write("\t\t\t\tdisplay:inline-block;\r\n");
      out.write("\t\t\t\tvertical-align:middle;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-group>.btn,.btn-group-vertical>.btn\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tposition:relative;\r\n");
      out.write("\t\t\t\tfloat:left;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-toolbar>.btn+.btn,.btn-toolbar>.btn-group+.btn,.btn-toolbar>.btn+.btn-group,.btn-toolbar>.btn-group+.btn-group\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tmargin-left:5px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-group-xs>.btn\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tfont-size:12px;\r\n");
      out.write("\t\t\t\tline-height:1.5;\r\n");
      out.write("\t\t\t\tborder-radius:2px;\r\n");
      out.write("\t\t\t\tpadding:1px 5px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-group>.btn+.dropdown-toggle\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tpadding-right:8px;\r\n");
      out.write("\t\t\t\tpadding-left:8px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-group>.btn-lg+.dropdown-toggle\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tpadding-right:12px;\r\n");
      out.write("\t\t\t\tpadding-left:12px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-group.open .dropdown-toggle\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t-webkit-box-shadow:inset 0 3px 5px rgba(0,0,0,.125);\r\n");
      out.write("\t\t\t\tbox-shadow:inset 0 3px 5px rgba(0,0,0,.125);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-group-vertical>.btn,.btn-group-vertical>.btn-group\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdisplay:block;\r\n");
      out.write("\t\t\t\tfloat:none;\r\n");
      out.write("\t\t\t\twidth:100%;\r\n");
      out.write("\t\t\t\tmax-width:100%;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-group-vertical>.btn+.btn,.btn-group-vertical>.btn+.btn-group,.btn-group-vertical>.btn-group+.btn,.btn-group-vertical>.btn-group+.btn-group\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tmargin-top:-1px;\r\n");
      out.write("\t\t\t\tmargin-left:0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-group-vertical>.btn:first-child:not(:last-child)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tborder-top-right-radius:2px;\r\n");
      out.write("\t\t\t\tborder-bottom-right-radius:0;\r\n");
      out.write("\t\t\t\tborder-bottom-left-radius:0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-group-vertical>.btn:last-child:not(:first-child)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tborder-top-left-radius:0;\r\n");
      out.write("\t\t\t\tborder-top-right-radius:0;\r\n");
      out.write("\t\t\t\tborder-bottom-left-radius:2px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-group-vertical>.btn-group:first-child>.btn:last-child,.btn-group-vertical>.btn-group:first-child>.dropdown-toggle\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tborder-bottom-right-radius:0;\r\n");
      out.write("\t\t\t\tborder-bottom-left-radius:0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.btn-group-vertical>.btn-group:last-child>.btn:first-child\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tborder-top-left-radius:0;\r\n");
      out.write("\t\t\t\tborder-top-right-radius:0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t@media (min-width: 768px){\r\n");
      out.write("\t\t\t\t#header {\r\n");
      out.write("\t\t\t\t\twidth: 750px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t@media (min-width: 992px){\r\n");
      out.write("\t\t\t\t#header {\r\n");
      out.write("\t\t\t\t\twidth: 970px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t@media (min-width: 1200px){\r\n");
      out.write("\t\t\t\t#header {\r\n");
      out.write("\t\t\t\t\twidth: 1170px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#logo{\r\n");
      out.write("\t\t\t\tpadding-left: 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#header {\r\n");
      out.write("\t\t\t\tmargin:0 auto;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#header.sticky-header .container{\r\n");
      out.write("\t\t\t\tpadding:0 10px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- jQuery -->\r\n");
      out.write("\t\t<script src=\"rweb/assets/js/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write(" <body class=\"sticky-header-on tablet-sticky-header\" style=\"padding-bottom:0;\tfont-size:medium\r\n");
      out.write("; line-height: 1.5em\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"fb-root\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Container -->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Header -->\r\n");
      out.write("\t\t\t<header id=\"\" class=\"sticky-header\" style=\"opacity: 1;padding:0;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Main Header -->\r\n");
      out.write("\t\t\t\t<div id=\"main-header\" style=\"height: 80px;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"logo\" class=\"col-lg-12 col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"static/image/b2.png\" style=\"width: 110px;margin-top: -20px;margin-right: -20px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<span style=\"color:white;font-size:33px;margin-top: 1px;\">Network Fingerprint Scanner</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span style=\"color: white; font-size: 15px; top: 28px; margin-left: 5px;\">NFPscanner：a server for knowledge-based characterization of biomedical networks\r\n");
      out.write("</span> <span style=\"position:absolute;right:10;top:6;display: none;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          //  c:when
          org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
          _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
          _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          // /WEB-INF/views/rweb/networksimilarity/networksimilarityHome.jsp(470,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
          int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
          if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"btn-user\"><i class=\"fa fa-user\"></i> ");
              out.print(session.getAttribute("username") );
              out.write("</button>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"logout()\" id=\"btn-out\"><i class=\"fa  fa-user-md\"></i> Log Out</button>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
            return;
          }
          _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /Main Header -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Lower Header -->\r\n");
      out.write("\t\t\t\t<div id=\"lower-header\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"menu-button\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span>Menu</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul id=\"navigation\" style=\"\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Home -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"current-menu-item\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa \" href=\"networksimilarityHome\">Home</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- /home -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Events -->\r\n");
      out.write("\t\t\t\t\t\t<li  style=\"width: 300px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityAnalysis?type=1\">Network Fingerprint Scan</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"width: 250px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityAnalysis?type=2\">Pairwise Alignment</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- /Events -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Media -->\r\n");
      out.write("\t\t\t\t\t\t<!-- /Media -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Features -->\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa \" href=\"networksimilaritystatistical\">Resource</a>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- /Features -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Get Involved -->\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityHelp\">Help</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- /Get Involved -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- CONTACT -->\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityContact\">Contact</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- /CONTACT -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /Lower Header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t<!-- /Header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<section id=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Section -->\r\n");
      out.write("\t\t\t<section class=\"section full-width-bg\" style=\"padding-top:20px\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t<h3 style=\"text-align:center\">Welcome to NFPscanner</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"intro\">\r\n");
      out.write("\t\t\t\t\t \t<p style=\"line-height:1.5em\">\r\n");
      out.write("Network Fingerprint Scanner (NFPscanner) is a web server to decipher biomedical networks by making systematic comparisons to well-studied basic networks. A given biomedical network is characterized as a spectrum-like vector called “network fingerprint”, which contains similarities to basic networks. The similarity is measured by conservations of protein-protein interactions (PPI), sequence and functional annotations. This knowledge-based multidimensional characterization provides an intuitive way to decipher molecular networks, especially for large-scale network comparison and clustering analyses. <br/>\r\n");
      out.write("The NFPscanner has three highlighted features:<br/>\r\n");
      out.write("<ol>\r\n");
      out.write("\t<li>\r\n");
      out.write("Incorporation of 4 network alignment algorithms (\r\n");
      out.write("<a href=\"networksimilarityHelp#APcluster\">APcluster</a>,  \r\n");
      out.write("<a href=\"networksimilarityHelp#IsoRankN\">IsoRankN</a>, \r\n");
      out.write("<a href=\"networksimilarityHelp#SPINAL\">SPINAL</a>, \r\n");
      out.write("<a href=\"networksimilarityHelp#GHOST\">GHOST</a>);\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li>\r\n");
      out.write("Manually curated 49 sets of basic networks, retrieved from 6 network databases (\r\n");
      out.write("<a href=\"http://www.genome.jp/kegg/\">KEGG</a>,  \r\n");
      out.write("<a href=\"http://www.reactome.org/\">Reactome</a>,  \r\n");
      out.write("<a href=\"http://pid.nci.nih.gov/\">NCI/PID</a>,  \r\n");
      out.write("<a href=\"http://www.cs.tau.ac.il/~spike/\">SPIKE</a>,  \r\n");
      out.write("<a href=\"http://humancyc.org/\">HumanCyc</a>,  \r\n");
      out.write("<a href=\"http://pantherdb.org/\">PANTHER</a>,\r\n");
      out.write("<a href=\"http://cgap.nci.nih.gov/Pathways/BioCarta_Pathways/\">BioCarta</a>\r\n");
      out.write(");\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li>\r\n");
      out.write("Visualization of \r\n");
      out.write("<a href=\"networksimilarityHelp#UnderstandbodyA\">network fingerprint </a>\r\n");
      out.write("and \r\n");
      out.write("<a href=\"networksimilarityHelp#ExplorebodyA\">pairwise alignment </a>.<br/>\r\n");
      out.write("\t</li>\r\n");
      out.write("</ol>\r\n");
      out.write("You are always welcome to improve NFPscanner service by commenting, contribute alignment algorithms and/or special basic network sets. Feel free to \r\n");
      out.write("<a href=\"networksimilarityContact\">contact us</a>\r\n");
      out.write("if you have any comments or questions on this web server.\r\n");
      out.write("\t\t\t\t\t \t</p>\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t<img src='static/image/home1.jpg'/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-4 sidebar\" style=\"padding-right:15px;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sidebar-box white \" style=\"opacity: 1;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Quick Start </h3>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>New to NFPscanner? Try the tutorials now.</h4>\r\n");
      out.write("             \t\t\t\t <a href=\"javascript:void(0);\" onclick=\"playtour(1)\" class=\"btn btn-primary\" style=\"margin-bottom:0.5em\"><span class=\"glyphicon glyphicon-play\" aria-hidden=\"true\"></span>&nbsp;Tutorial for Fingerprint Scan</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:void(0);\" onclick=\"playtour(2)\" class=\"btn btn-primary\" ><span class=\"glyphicon glyphicon-play \" aria-hidden=\"true\"></span>&nbsp;Tutorial for Pairwise Alignment</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- /Featured Video -->\r\n");
      out.write("\t\t\t\t\t\t<!-- Featured Video -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sidebar-box white\" style=\"opacity: 1;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Statistics</h3>\r\n");
      out.write("              <h4>NFPscanner webserver contains:</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 style=\"display:inline\"> 2 </h4> analysis tools <br>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 style=\"display:inline\"> 4 </h4> alignment algorithms<br>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 style=\"display:inline\"> 49 </h4> set of basic networks from <h4 style=\"display:inline\"> 7 </h4> databases\r\n");
      out.write("              </p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /Featured Video -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Upcoming Events -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sidebar-box white\" style=\"opacity: 1;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>What’s New?</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"upcoming-events\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Event -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"event-content\">\r\n");
      out.write("                    <h4><a href=\"networksimilarityNews\">Version 1.4 online. </a></h4>\r\n");
      out.write("                    <ul class=\"event-meta\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"icons icon-clock\"></i>30th November 2015</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("                    Server web interface and help page is updated.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"event-content\">\r\n");
      out.write("                    <h4><a href=\"networksimilarityNews\"> Version 1.3 online.</a></h4>\r\n");
      out.write("                    <ul class=\"event-meta\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><i class=\"icons icon-clock\"></i>10th November 2015</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("                     Example data are deployed. Step-by-step tutorial guides are implemented. \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /Event -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"networksimilarityNews\" class=\"button transparent button-arrow\">More events</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<!-- /Section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Footer -->\r\n");
      out.write("\t\t\t<footer id=\"footer1\" >\r\n");
      out.write("\t\t\t\t<!-- Lower Footer -->\r\n");
      out.write("\t\t\t\t<div id=\"lower-footer\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-left: 98%\">\t\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\" src=\"//ra.revolvermaps.com/0/0/3.js?i=0eu6839u0la&amp;b=0&amp;s=26&amp;m=2&amp;cl=ffffff&amp;co=010020&amp;cd=aa0000&amp;v0=60&amp;v1=60&amp;r=1\" async=\"async\"></script>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-4\" style=\"opacity: 1;width: 100%;\">\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<p class=\"copyright\">© 2014 Candidate. All Rights Reserved.More Templates <a href=\"http://www.baidu.com/\" target=\"_blank\" title=\"模板\">testtt</a> - Collect from <a href=\"http://www.cssmoban.com/\" title=\"网页模板\" target=\"_blank\">template</a></p>\r\n");
      out.write(" -->\t\t\t\t\t\t\t<div align=\"center\">\r\n");
      out.write(" \t\t\t\t\t\t\t\t <p class=\"copyright\">NFPscanner is supported by a grant from National Nature Science Foundation of China.\r\n");
      out.write("\t\t\t\t\t\t\t\t </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t <p class=\"copyright\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Copyright © 2015-2016 Beijing Institute of Radiation Medicine</p>\r\n");
      out.write(" \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t\t<div class=\"col-lg-8 col-md-8 col-sm-8\" style=\"opacity: 1;width: 255px;float: right;display: none\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"social-media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"social-icons\" style=\"margin-top:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"facebook\"><a href=\"#\" class=\"tooltip-ontop\" title=\"\" data-original-title=\"Facebook\"><i class=\"icons icon-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"twitter\"><a href=\"#\" class=\"tooltip-ontop\" title=\"\" data-original-title=\"Twitter\"><i class=\"icons icon-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"google\"><a href=\"#\" class=\"tooltip-ontop\" title=\"\" data-original-title=\"Google Plus\"><i class=\"icons icon-gplus\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"youtube\"><a href=\"#\" class=\"tooltip-ontop\" title=\"\" data-original-title=\"Youtube\"><i class=\"icons icon-youtube-1\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"flickr\"><a href=\"#\" class=\"tooltip-ontop\" title=\"\" data-original-title=\"Flickr\"><i class=\"icons icon-flickr-4\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"email\"><a href=\"#\" class=\"tooltip-ontop\" title=\"\" data-original-title=\"Email\"><i class=\"icons icon-mail\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"social-buttons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"fb-share-button fb_iframe_widget\" data-href=\"https://developers.facebook.com/docs/plugins/\" data-type=\"button_count\" fb-xfbml-state=\"rendered\" fb-iframe-plugin-query=\"app_id=&amp;container_width=0&amp;href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;locale=en_US&amp;sdk=joey&amp;type=button_count\"><span style=\"vertical-align: top; width: 0px; height: 0px; overflow: hidden;\"><iframe name=\"f22cb15388\" width=\"1000px\" height=\"1000px\" frameborder=\"0\" allowtransparency=\"true\" allowfullscreen=\"true\" scrolling=\"no\" title=\"fb:share_button Facebook Social Plugin\" src=\"http://www.facebook.com/plugins/share_button.php?app_id=&amp;channel=http%3A%2F%2Fstatic.ak.facebook.com%2Fconnect%2Fxd_arbiter%2F44OwK74u0Ie.js%3Fversion%3D41%23cb%3Df33b497b24%26domain%3Ddemo.cssmoban.com%26origin%3Dhttp%253A%252F%252Fdemo.cssmoban.com%252Ff24389cf2c%26relation%3Dparent.parent&amp;container_width=0&amp;href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;locale=en_US&amp;sdk=joey&amp;type=button_count\" style=\"border: none; visibility: visible; width: 0px; height: 0px;\"></iframe></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /Lower Footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\t\t<!-- /Footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Back To Top -->\r\n");
      out.write("<!-- \t\t\t<a href=\"#\" id=\"button-to-top\" style=\"display: none;\"><i class=\"icons icon-up-dir\"></i></a>\r\n");
      out.write(" -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "login.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- /Container -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- JavaScript -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Bootstrap -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"rweb/assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Modernizr -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"rweb/assets/js/modernizr.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Sliders/Carousels -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"rweb/assets/js/jquery.flexslider-min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"rweb/assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Main Script -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"rweb/assets/js/script.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"static/js/scrollspy.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction playtour(type){\r\n");
      out.write("\t\t\tsetCookie(\"play\",type);\r\n");
      out.write("\t\t\twindow.location.href = \"networksimilarityAnalysis?type=\" + type + \"&play=\" + type;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction setCookie(name,value) \r\n");
      out.write("\t\t{ \r\n");
      out.write("\t\t\tvar Days = 30; \r\n");
      out.write("\t\t\tvar exp = new Date(); \r\n");
      out.write("\t\t\texp.setTime(exp.getTime() + Days*24*60*60*1000); \r\n");
      out.write("\t\t\tdocument.cookie = name + \"=\"+ escape (value) + \";expires=\" + exp.toGMTString(); \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<!--[if lt IE 9]>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\" src=\"rweb/assets/js/jquery.placeholder.js\"></script>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\" src=\"rweb/assets/js/script_ie.js\"></script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"btn-login\" data-toggle=\"modal\" data-target=\"#loginModal\"><i class=\"fa fa-lightbulb-o\"></i> Login</button>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"btn-signup\" data-toggle=\"modal\" data-target=\"#signupModal\"><i class=\"fa  fa-user-md\"></i> Sign Up</button>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f1.setParent(null);
    int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
    if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    // /WEB-INF/views/rweb/networksimilarity/networksimilarityHome.jsp(532,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
    if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a id=\"resource1\" href=\"networksimilaritystatistical\">Statistics of current release</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a id=\"resource2\" href=\"networksimilarityprofiles\">My Profiles</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
    return false;
  }
}
