/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-12-21 00:54:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.rweb.networksimilarity;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class networksimilaritystatistical_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \t<meta charset=\"utf-8\">\r\n");
      out.write("\t    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t    <title>Network Fingerprint Scanner</title>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("        <link rel='stylesheet' type='text/css' href='http://fonts.useso.com/css?family=Open+Sans:400,700|Droid+Sans:400,700' />\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"static/image/w1.png\" />\r\n");
      out.write("\t\t<script src=\"rweb/assets/js/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("\t    <link rel=\"stylesheet\" type=\"text/css\" href=\"rweb/assets/js/bootstrap-fileupload/bootstrap-fileupload.min.css\" />\r\n");
      out.write("\t\t<link href=\"rweb/css/header.css\"  type=\"text/css\" rel=\"stylesheet\">\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"rweb/assets/js/bootstrap-fileupload/bootstrap-fileupload.min.js\"></script>\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/climacons-font.css\" rel=\"stylesheet\">\r\n");
      out.write("\t    <link href=\"rweb/assets/css/style.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/style.css\" rel=\"stylesheet\" type=\"text/css\">\t\r\n");
      out.write("\t\t<link href=\"rweb/css/header.css\"  type=\"text/css\" rel=\"stylesheet\">\t\r\n");
      out.write("\t\t<link href=\"rweb/css/comment.css\" rel=\"stylesheet\">\t\r\n");
      out.write("\t\t<link href=\"rweb/js/jquery-datatables/jquery.dataTables.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"rweb/assets/css/bootstrap.min.css\" rel=\"stylesheet\">\t\t\r\n");
      out.write("\t\t<link href=\"rweb/assets/js/bootstrap-table.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tif (navigator.userAgent.split(\";\")[1].toLowerCase().indexOf(\"msie\") > 0 ){\r\n");
      out.write("\t\t\t\talert(\"A problem with your browser\\n You are using a very old version of Internet Explorer.\\n We recommend you upgrade to an alternative browser than Internet Explorer.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\t.action-item {\r\n");
      out.write("\t\t\t    display: inline-block;\r\n");
      out.write("\t\t\t    padding-right: .5rem;\r\n");
      out.write("\t\t\t    padding-left: .25rem;\r\n");
      out.write("\t\t\t    border-right-width: 1px;\r\n");
      out.write("\t\t\t    border-right-style: solid;\r\n");
      out.write("\t\t\t\t    line-height: 1.25rem;\r\n");
      out.write("\t\t\t    font-size: 1rem;\r\n");
      out.write("\t\t\t    color: #999;\r\n");
      out.write("\t\t\t    text-transform: uppercase;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.action-item a{\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.radio-inline, .checkbox-inline{\r\n");
      out.write("\t\t\t\tline-height:22px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"font-size:medium; line-height: 1.5em\">\r\n");
      out.write("\t<div class=\"container\" >\r\n");
      out.write("\t\t\t<!-- Header -->\r\n");
      out.write("\t\t\t<header id=\"\" class=\"sticky-header\" style=\"opacity: 1;padding:0;\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Main Header -->\r\n");
      out.write("\t\t\t\t<div id=\"main-header\" style=\"height: 80px;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"logo\" class=\"col-lg-12 col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"static/image/b2.png\" style=\"width: 110px;margin-top: -20px;margin-right: -20px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<span style=\"color:white;font-size:33px;margin-top: 1px;\">Network Fingerprint Scanner</span> \r\n");
      out.write("\t\t\t\t\t\t\t<span style=\"color: white; font-size: 15px; top: 28px; margin-left: 5px;\">NFPscanner：a server for knowledge-based characterization of biomedical networks\r\n");
      out.write("</span> <span style=\"position:absolute;right:10;top:6;display: none;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          //  c:when
          org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
          _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
          _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          // /WEB-INF/views/rweb/networksimilarity/networksimilaritystatistical.jsp(72,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
          int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
          if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"btn-user\"><i class=\"fa fa-user\"></i> ");
              out.print(session.getAttribute("username") );
              out.write("</button>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"logout()\" id=\"btn-out\"><i class=\"fa  fa-user-md\"></i> Log Out</button>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
            return;
          }
          _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /Main Header -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Lower Header -->\r\n");
      out.write("\t\t\t\t<div id=\"lower-header\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"menu-button\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span>Menu</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul id=\"navigation\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- Home -->\r\n");
      out.write("\t\t\t\t\t\t<li >\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa \" href=\"networksimilarityHome\">Home</a>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- /home -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- Events -->\r\n");
      out.write("\t\t\t\t\t\t<li  style=\"width: 300px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityAnalysis?type=1\">Network Fingerprint Scan</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"width: 250px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityAnalysis?type=2\">Pairwise Alignment</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- /Events -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- Media -->\r\n");
      out.write("\t\t\t\t\t\t<!-- /Media -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- Features -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"current-menu-item\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa \" href=\"networksimilaritystatistical\">Resource</a>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- /Features -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- Get Involved -->\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityHelp\">Help</a>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- /Get Involved -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- CONTACT -->\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"fa  \" href=\"networksimilarityContact\">Contact</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- /CONTACT -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /Lower Header -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t<!-- /Header -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<section id=\"content\" style=\"min-height:800px;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Section -->\r\n");
      out.write("\t\t\t<section class=\"section full-width-bg\" style=\"padding-top:20px;min-height:800px;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<ol class=\"breadcrumb\" id=\"breadcrumb\" style=\"margin:10px 0 0 0;display: none;\">\r\n");
      out.write("\t\t\t\t\t<li><!-- <i class=\"fa fa-edit\"></i> --><a style=\"font-size: 15px;\">Resource</a></li>\r\n");
      out.write("\t\t\t\t\t<li><!-- <i class=\"fa fa-th\"></i> --><span id=\"analysisName\" style=\"font-size: 15px;\">Statistics of current release</span></li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"margin-top: 15px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel panel-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-heading\" style=\"background: #337ab7;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <i class=\"fa fa-random red\"></i> --><strong><font color=\"white\">Library of basic networks:</font></strong>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-body\" style=\"padding:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"height: 555px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table id=\"systemRefNet\" class=\"table table-striped table-bordered table-condensed\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!--");
      if (_jspx_meth_c_005fchoose_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t-->\r\n");
      out.write("<!-- \t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel panel-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-heading\" style=\"background: #337ab7;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2><i class=\"fa fa-random red\"></i><span class=\"break\"></span><strong><font color=\"white\">\r\n");
      out.write("\t\t\t\t\t\t\t\tChart with points</font></strong></h2>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>/col\r\n");
      out.write("\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "login.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Footer -->\r\n");
      out.write("\t\t\t<footer id=\"footer1\" >\t\r\n");
      out.write("\t\t\t\t<!-- Lower Footer -->\r\n");
      out.write("\t\t\t\t<div id=\"lower-footer\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-left: 98%\">\t\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\" src=\"//ra.revolvermaps.com/0/0/3.js?i=0eu6839u0la&amp;b=0&amp;s=26&amp;m=2&amp;cl=ffffff&amp;co=010020&amp;cd=aa0000&amp;v0=60&amp;v1=60&amp;r=1\" async=\"async\"></script>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-4\" style=\"opacity: 1;width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<p class=\"copyright\">© 2014 Candidate. All Rights Reserved.More Templates <a href=\"http://www.baidu.com/\" target=\"_blank\" title=\"模板\">testtt</a> - Collect from <a href=\"http://www.cssmoban.com/\" title=\"网页模板\" target=\"_blank\">template</a></p>\r\n");
      out.write(" -->\t\t\t\t\t\t\t<div align=\"center\">\r\n");
      out.write(" \t\t\t\t\t\t\t\t <p class=\"copyright\">NFPscanner is supported by a grant from National Nature Science Foundation of China.\r\n");
      out.write("\t\t\t\t\t\t\t\t </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t <p class=\"copyright\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Copyright © 2015-2016 Beijing Institute of Radiation Medicine</p>\r\n");
      out.write(" \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t<!-- \t\t\t\t<div class=\"col-lg-8 col-md-8 col-sm-8\" style=\"opacity: 1;width: 255px;float: right;display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"social-media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"social-icons\" style=\"margin-top:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"facebook\"><a href=\"#\" class=\"tooltip-ontop\" title=\"\" data-original-title=\"Facebook\"><i class=\"icons icon-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"twitter\"><a href=\"#\" class=\"tooltip-ontop\" title=\"\" data-original-title=\"Twitter\"><i class=\"icons icon-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"google\"><a href=\"#\" class=\"tooltip-ontop\" title=\"\" data-original-title=\"Google Plus\"><i class=\"icons icon-gplus\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"youtube\"><a href=\"#\" class=\"tooltip-ontop\" title=\"\" data-original-title=\"Youtube\"><i class=\"icons icon-youtube-1\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"flickr\"><a href=\"#\" class=\"tooltip-ontop\" title=\"\" data-original-title=\"Flickr\"><i class=\"icons icon-flickr-4\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"email\"><a href=\"#\" class=\"tooltip-ontop\" title=\"\" data-original-title=\"Email\"><i class=\"icons icon-mail\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"social-buttons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"fb-share-button fb_iframe_widget\" data-href=\"https://developers.facebook.com/docs/plugins/\" data-type=\"button_count\" fb-xfbml-state=\"rendered\" fb-iframe-plugin-query=\"app_id=&amp;container_width=0&amp;href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;locale=en_US&amp;sdk=joey&amp;type=button_count\"><span style=\"vertical-align: top; width: 0px; height: 0px; overflow: hidden;\"><iframe name=\"f22cb15388\" width=\"1000px\" height=\"1000px\" frameborder=\"0\" allowtransparency=\"true\" allowfullscreen=\"true\" scrolling=\"no\" title=\"fb:share_button Facebook Social Plugin\" src=\"http://www.facebook.com/plugins/share_button.php?app_id=&amp;channel=http%3A%2F%2Fstatic.ak.facebook.com%2Fconnect%2Fxd_arbiter%2F44OwK74u0Ie.js%3Fversion%3D41%23cb%3Df33b497b24%26domain%3Ddemo.cssmoban.com%26origin%3Dhttp%253A%252F%252Fdemo.cssmoban.com%252Ff24389cf2c%26relation%3Dparent.parent&amp;container_width=0&amp;href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;locale=en_US&amp;sdk=joey&amp;type=button_count\" style=\"border: none; visibility: visible; width: 0px; height: 0px;\"></iframe></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /Lower Footer -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\t\t<!-- /Footer -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t<div class=\"modal fade\" id=\"tipModal2222\" style=\"top:15%;\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"selectFileModalLabel\">\r\n");
      out.write("\t  <div class=\"modal-dialog\" style=\"border:none;width: 1000px;\" role=\"document\" >\r\n");
      out.write("\t\t<div class=\"box border\">\r\n");
      out.write("\t\t\t<div class=\"box-title\">\r\n");
      out.write("\t\t\t\t<h4><i class=\"fa fa-check-square-o\"></i>Tip</h4>\r\n");
      out.write("\t\t\t\t<div class=\"tools\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\" data-dismiss=\"modal\" aria-label=\"Close\" class=\"remove\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"box-body\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("                    <div class=\"form-group\"  align=\"center\">\r\n");
      out.write("                       <div style='height: 450px;width: 999px;'>\r\n");
      out.write("                       \t\t<table id='systemContent' class='table table-striped table-bordered table-condensed'></table>\r\n");
      out.write("                       </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\" style=\"padding: 10px 0 0 0;margin-top:0px;\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\" aria-label=\"Close\" >OK</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t");
      out.write("<!-- start: JavaScript-->\r\n");
      out.write("\t<script src=\"rweb/assets/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"rweb/assets/js/bootstrap.min.js\"></script>\t\r\n");
      out.write("\t<script src=\"rweb/assets/js/bootstrap-table.js\"></script>\t\r\n");
      out.write("<!-- \t\t<script src=\"rweb/assets/js/bootstrap-table-zh-CN.js\"></script>\t\r\n");
      out.write(" -->\t\r\n");
      out.write("\t<script type=\"text/javascript\" charset=\"utf8\" src=\"rweb/js/jquery-datatables/jquery.dataTables.js\"></script>\r\n");
      out.write("\t<script src=\"static/js/SystemRefNet.js\"></script>\r\n");
      out.write("\t<!-- end: JavaScript-->\r\n");
      out.write("\t<script>\r\n");
      out.write("\tvar libraryNet = '");
      out.print(request.getParameter("libraryNet"));
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"btn-login\" data-toggle=\"modal\" data-target=\"#loginModal\"><i class=\"fa fa-lightbulb-o\"></i> Login</button>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"btn-signup\" data-toggle=\"modal\" data-target=\"#signupModal\"><i class=\"fa  fa-user-md\"></i> Sign Up</button>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f1.setParent(null);
    int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
    if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    // /WEB-INF/views/rweb/networksimilarity/networksimilaritystatistical.jsp(135,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
    if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a id=\"resource1\" href=\"networksimilaritystatistical\">Statistics of current release</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<li><a id=\"resource2\" href=\"networksimilarityprofiles\">My Profiles</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f2.setParent(null);
    int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
    if (_jspx_eval_c_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
    // /WEB-INF/views/rweb/networksimilarity/networksimilaritystatistical.jsp(201,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
    if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
        out.write("\t\t\t\t\t\t\t\t<div class=\"panel panel-info\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-random red\"></i><strong>User Ref Net:</strong>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</div>\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel-body\" style=\"padding:0;\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<table class=\"table table-bordered table-striped table-condensed table-hover\" id=\"userTable\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t  <thead>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t  <tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t <th>Avaliable RefNet</th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t <th>Type</th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t <th>Number</th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t <th>Porpularity</th>                                          \r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t  </tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t  </thead>   \r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t  <tbody>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t  </tbody>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t </table>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f2 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
    int _jspx_eval_c_005fotherwise_005f2 = _jspx_th_c_005fotherwise_005f2.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
    return false;
  }
}
